package com.spdb.migration;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.support.JdbcTransactionManager;
import org.springframework.beans.BeanUtils;

import static org.assertj.core.api.Assertions.assertThat;

class MigrationTranCodeLookbackDaysTest {

    @Test
    void formHasSingleResolvableConstructorForSpringMvcBinding() {
        assertThat(BeanUtils.getResolvableConstructor(MigrationTranCodeCommandForm.class).getParameterCount())
                .isEqualTo(5);
    }

    @Test
    void persistsConfiguredLookbackDaysAndUsesRequestedParallelism() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:migration_tran_code_lookback;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "sa", ""
        );
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        jdbc.execute("""
                create table ana_migration_command (
                    command_id bigint generated by default as identity primary key,
                    source_data_source varchar(64) not null,
                    target_data_source varchar(64) not null,
                    command_type varchar(32) not null,
                    time_from bigint not null,
                    time_to bigint not null,
                    window_seconds bigint not null,
                    parallelism integer not null,
                    status varchar(32) not null,
                    total_shard_count bigint not null,
                    tran_codes clob,
                    sample_size integer,
                    lookback_days integer,
                    remark varchar(1000),
                    created_by varchar(100),
                    created_time timestamp default current_timestamp,
                    updated_at timestamp default current_timestamp
                )
                """);
        jdbc.execute("""
                create table ana_migration_shard (
                    shard_id bigint generated by default as identity primary key,
                    command_id bigint not null,
                    shard_seq integer not null,
                    tran_code varchar(32),
                    time_from bigint not null,
                    time_to bigint not null,
                    status varchar(32) not null
                )
                """);

        MigrationCommandService service = new MigrationCommandService(
                new NamedParameterJdbcTemplate(dataSource),
                new JdbcTransactionManager(dataSource),
                emptyLauncherProvider(),
                new MigrationRuntimeProperties("bxds", "primary")
        );

        long commandId = service.createTranCodeCommand(
                new MigrationTranCodeCommandForm("A001", 10, 9, 16, "lookback test")
        );

        assertThat(jdbc.queryForObject(
                "select lookback_days from ana_migration_command where command_id = ?", Integer.class, commandId
        )).isEqualTo(9);
        assertThat(jdbc.queryForObject(
                "select parallelism from ana_migration_command where command_id = ?", Integer.class, commandId
        )).isEqualTo(16);
        assertThat(MigrationTranCodeCommandForm.empty().lookbackDays()).isEqualTo(5);
        assertThat(MigrationTranCodeCommandForm.empty().parallelism()).isEqualTo(8);
    }

    private ObjectProvider<MigrationTaskLauncher> emptyLauncherProvider() {
        return new ObjectProvider<>() {
            @Override
            public MigrationTaskLauncher getObject(Object... args) {
                return null;
            }

            @Override
            public MigrationTaskLauncher getIfAvailable() {
                return null;
            }

            @Override
            public MigrationTaskLauncher getIfUnique() {
                return null;
            }

            @Override
            public MigrationTaskLauncher getObject() {
                return null;
            }
        };
    }
}
