package com.spdb.migration;

import com.spdb.web.PageRequestParams;
import com.spdb.web.PagedResult;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.reset;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class MigrationCommandServiceTest {
    private NamedParameterJdbcTemplate jdbc;
    private JdbcTemplate plainJdbc;
    private MigrationCommandService service;
    private MigrationTaskLauncher launcher;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:migration_command;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        jdbc = new NamedParameterJdbcTemplate(dataSource);
        plainJdbc = new JdbcTemplate(dataSource);
        plainJdbc.execute("drop table if exists ana_migration_shard");
        plainJdbc.execute("drop table if exists ana_migration_command");
        plainJdbc.execute("""
                create table ana_migration_command (
                    command_id bigint generated by default as identity primary key,
                    source_label varchar(64) not null,
                    target_schema varchar(64) not null,
                    time_from bigint not null,
                    time_to bigint not null,
                    window_seconds bigint not null,
                    parallelism integer not null,
                    status varchar(32) not null,
                    total_shard_count bigint not null default 0,
                    completed_shard_count bigint not null default 0,
                    failed_shard_count bigint not null default 0,
                    migrated_rows bigint not null default 0,
                    skipped_rows bigint not null default 0,
                    dropped_rows bigint not null default 0,
                    error_message varchar(2000),
                    remark varchar(1000),
                    created_by varchar(100),
                    created_time timestamp default current_timestamp,
                    started_time timestamp,
                    ended_time timestamp,
                    updated_at timestamp default current_timestamp
                )
                """);
        plainJdbc.execute("""
                create table ana_migration_shard (
                    shard_id bigint generated by default as identity primary key,
                    command_id bigint not null,
                    shard_seq integer not null,
                    time_from bigint not null,
                    time_to bigint not null,
                    status varchar(32) not null,
                    migrated_rows bigint not null default 0,
                    skipped_rows bigint not null default 0,
                    dropped_rows bigint not null default 0,
                    error_message varchar(2000),
                    attempts integer not null default 0,
                    created_time timestamp default current_timestamp,
                    started_time timestamp,
                    ended_time timestamp,
                    updated_at timestamp default current_timestamp
                )
                """);
        launcher = mock(MigrationTaskLauncher.class);
        ObjectProvider<MigrationTaskLauncher> provider = launcherProvider();
        when(provider.getIfAvailable()).thenReturn(launcher);
        service = new MigrationCommandService(
                jdbc,
                new DataSourceTransactionManager(dataSource),
                provider,
                new MigrationRuntimeProperties("bxds", "tss")
        );
    }

    @SuppressWarnings("unchecked")
    private ObjectProvider<MigrationTaskLauncher> launcherProvider() {
        return mock(ObjectProvider.class);
    }

    @Test
    void createCommandSplitsHalfOpenWindowsAndLaunches() {
        long commandId = service.createCommand(new MigrationCommandForm(100L, 250L, 60L, 2, "demo"));

        assertThat(commandId).isPositive();
        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_shard where command_id = " + commandId, Long.class))
                .isEqualTo(3L);
        assertThat(plainJdbc.queryForList("select time_from from ana_migration_shard where command_id = " + commandId + " order by shard_seq", Long.class))
                .containsExactly(100L, 160L, 220L);
        assertThat(plainJdbc.queryForList("select time_to from ana_migration_shard where command_id = " + commandId + " order by shard_seq", Long.class))
                .containsExactly(160L, 220L, 250L);
        verify(launcher).launch(commandId);
    }

    @Test
    void createCommandRejectsInvalidForms() {
        assertThatThrownBy(() -> service.createCommand(null))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(200L, 200L, 60L, 2, "demo")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(200L, 199L, 60L, 2, "demo")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(100L, 200L, 0L, 2, "demo")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(100L, 200L, 60L, 0, "demo")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(100L, 200L, 60L, 9, "demo")))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("并行度");
    }

    @Test
    void createCommandRollsBackCommandWhenShardInsertFails() {
        plainJdbc.execute("alter table ana_migration_shard add constraint ck_test_shard_time_to check (time_to < 200)");

        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(100L, 220L, 60L, 2, "rollback")))
                .isInstanceOf(RuntimeException.class);

        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_command", Long.class))
                .isZero();
        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_shard", Long.class))
                .isZero();
        verify(launcher, never()).launch(1L);
    }

    @Test
    void createCommandRejectsExcessiveAndOverflowingShardRangesBeforeInsert() {
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(0L, 10_001L, 1L, 2, "too many")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(0L, Long.MAX_VALUE, Long.MAX_VALUE - 1L, 2, "overflow count")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(Long.MAX_VALUE - 2L, Long.MAX_VALUE, Long.MAX_VALUE, 2, "overflow window")))
                .isInstanceOf(IllegalArgumentException.class);

        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_command", Long.class))
                .isZero();
        verify(launcher, never()).launch(1L);
    }

    @Test
    void searchReturnsCommandRowsAndPageMetadata() {
        long firstCommandId = service.createCommand(new MigrationCommandForm(100L, 220L, 60L, 2, "first"));
        long secondCommandId = service.createCommand(new MigrationCommandForm(300L, 420L, 60L, 4, "second"));

        PagedResult<MigrationCommandRow> result = service.search(PageRequestParams.of(1, 20));

        assertThat(result.total()).isEqualTo(2);
        assertThat(result.page()).isEqualTo(1);
        assertThat(result.size()).isEqualTo(20);
        assertThat(result.totalPages()).isEqualTo(1);
        assertThat(result.rows()).hasSize(2);
        assertThat(result.rows()).extracting(MigrationCommandRow::commandId)
                .containsExactly(secondCommandId, firstCommandId);
        assertThat(result.rows()).extracting(MigrationCommandRow::sourceLabel)
                .containsOnly("bxds");
        assertThat(result.rows()).extracting(MigrationCommandRow::targetSchema)
                .containsOnly("tss");
        assertThat(result.rows()).extracting(MigrationCommandRow::status)
                .containsOnly("CREATED");
        assertThat(result.rows()).extracting(MigrationCommandRow::totalShardCount)
                .containsExactly(2L, 2L);
    }

    @Test
    void searchClampsOutOfRangePageBeforeQueryingRows() {
        for (int i = 0; i < 21; i++) {
            long timeFrom = 100L + (i * 100L);
            service.createCommand(new MigrationCommandForm(timeFrom, timeFrom + 60L, 60L, 2, "command-" + i));
        }

        PagedResult<MigrationCommandRow> result = service.search(PageRequestParams.of(999, 20));

        assertThat(result.total()).isEqualTo(21);
        assertThat(result.totalPages()).isEqualTo(2);
        assertThat(result.page()).isEqualTo(2);
        assertThat(result.rows()).hasSize(1);
        assertThat(result.rows().get(0).sourceLabel()).isEqualTo("bxds");
        assertThat(result.rows().get(0).targetSchema()).isEqualTo("tss");
    }

    @Test
    void progressReturnsCommandAndShardRows() {
        long commandId = service.createCommand(new MigrationCommandForm(100L, 220L, 60L, 2, "demo"));

        MigrationProgressRow progress = service.progress(commandId);

        assertThat(progress.commandId()).isEqualTo(commandId);
        assertThat(progress.sourceLabel()).isEqualTo("bxds");
        assertThat(progress.targetSchema()).isEqualTo("tss");
        assertThat(progress.totalShardCount()).isEqualTo(2);
        assertThat(progress.shards()).hasSize(2);
    }

    @Test
    void cancelAndResumeUpdateCommandStatus() {
        long commandId = service.createCommand(new MigrationCommandForm(100L, 220L, 60L, 2, "demo"));
        reset(launcher);

        service.requestCancel(commandId);
        assertThat(service.progress(commandId).status()).isEqualTo("CANCEL_REQUESTED");

        service.resume(commandId);
        assertThat(service.progress(commandId).status()).isEqualTo("CREATED");
        verify(launcher).launch(commandId);
    }

    @Test
    void resumeDoesNotLaunchWhenStatusCannotBeResumed() {
        long createdCommandId = service.createCommand(new MigrationCommandForm(100L, 160L, 60L, 2, "created"));
        long completedCommandId = service.createCommand(new MigrationCommandForm(300L, 360L, 60L, 2, "completed"));
        setCommandStatus(completedCommandId, "COMPLETED");
        reset(launcher);

        service.resume(createdCommandId);
        service.resume(completedCommandId);
        service.resume(999999L);

        verify(launcher, never()).launch(createdCommandId);
        verify(launcher, never()).launch(completedCommandId);
        verify(launcher, never()).launch(999999L);
    }

    @Test
    void resumeRecoversStaleRunningCommandAndRunningShards() {
        long commandId = service.createCommand(new MigrationCommandForm(100L, 220L, 60L, 2, "stale running"));
        Long firstShardId = shardId(commandId, 0);
        Long secondShardId = shardId(commandId, 1);
        setCommandStatus(commandId, "RUNNING");
        setShardStatus(firstShardId, "RUNNING");
        setShardStatus(secondShardId, "COMPLETED");
        reset(launcher);

        service.resume(commandId);

        assertThat(service.progress(commandId).status()).isEqualTo("CREATED");
        assertThat(service.shard(firstShardId).status()).isEqualTo("FAILED");
        assertThat(service.shard(firstShardId).errorMessage()).contains("stale running shard reset for resume");
        assertThat(service.shard(secondShardId).status()).isEqualTo("COMPLETED");
        verify(launcher).launch(commandId);
    }

    @Test
    void terminalCommandHelpersUseStatusGuards() {
        long completedCommandId = service.createCommand(new MigrationCommandForm(100L, 160L, 60L, 2, "complete"));
        reset(launcher);

        service.markCompleted(completedCommandId);
        assertThat(service.progress(completedCommandId).status()).isEqualTo("CREATED");

        service.markRunning(completedCommandId);
        service.markCompleted(completedCommandId);
        assertThat(service.progress(completedCommandId).status()).isEqualTo("COMPLETED");

        service.markFailed(completedCommandId, "late failure");
        service.markCancelled(completedCommandId);
        assertThat(service.progress(completedCommandId).status()).isEqualTo("COMPLETED");

        long failedCommandId = service.createCommand(new MigrationCommandForm(200L, 260L, 60L, 2, "fail"));
        service.markRunning(failedCommandId);
        service.markFailed(failedCommandId, "failed");
        assertThat(service.progress(failedCommandId).status()).isEqualTo("FAILED");

        service.markCompleted(failedCommandId);
        service.markCancelled(failedCommandId);
        assertThat(service.progress(failedCommandId).status()).isEqualTo("FAILED");

        long createdCommandId = service.createCommand(new MigrationCommandForm(300L, 360L, 60L, 2, "created"));
        service.markCancelled(createdCommandId);
        assertThat(service.progress(createdCommandId).status()).isEqualTo("CANCELLED");

        long cancelRequestedCommandId = service.createCommand(new MigrationCommandForm(400L, 460L, 60L, 2, "cancel"));
        service.requestCancel(cancelRequestedCommandId);
        service.markCancelled(cancelRequestedCommandId);
        assertThat(service.progress(cancelRequestedCommandId).status()).isEqualTo("CANCELLED");
    }

    @Test
    void runnerFacingHelpersUpdateShardAndCommandState() {
        long commandId = service.createCommand(new MigrationCommandForm(100L, 220L, 60L, 2, "demo"));
        reset(launcher);
        Long firstShardId = shardId(commandId, 0);
        Long secondShardId = shardId(commandId, 1);

        service.markRunning(commandId);
        assertThat(service.progress(commandId).status()).isEqualTo("RUNNING");
        assertThat(service.tryStartShard(firstShardId)).isTrue();
        assertThat(service.tryStartShard(firstShardId)).isFalse();
        assertThat(service.shard(firstShardId).status()).isEqualTo("RUNNING");
        assertThat(service.shard(firstShardId).attempts()).isEqualTo(1);

        service.markShardCompleted(firstShardId, 10L, 2L, 1L);
        MigrationShardRow completedShard = service.shard(firstShardId);
        assertThat(completedShard.status()).isEqualTo("COMPLETED");
        assertThat(completedShard.migratedRows()).isEqualTo(10L);
        assertThat(completedShard.skippedRows()).isEqualTo(2L);
        assertThat(completedShard.droppedRows()).isEqualTo(1L);

        assertThat(service.tryStartShard(secondShardId)).isTrue();
        service.markShardFailed(secondShardId, "boom");
        assertThat(service.shard(secondShardId).status()).isEqualTo("FAILED");
        assertThat(service.shard(secondShardId).errorMessage()).isEqualTo("boom");

        service.refreshCommandCounters(commandId);
        MigrationProgressRow progress = service.progress(commandId);
        assertThat(progress.completedShardCount()).isEqualTo(1L);
        assertThat(progress.failedShardCount()).isEqualTo(1L);
        assertThat(progress.migratedRows()).isEqualTo(10L);
        assertThat(progress.skippedRows()).isEqualTo(2L);
        assertThat(progress.droppedRows()).isEqualTo(1L);

        assertThat(service.isCancelRequested(commandId)).isFalse();
        service.requestCancel(commandId);
        assertThat(service.isCancelRequested(commandId)).isTrue();
    }

    private void setCommandStatus(long commandId, String status) {
        plainJdbc.update("update ana_migration_command set status = ? where command_id = ?", status, commandId);
    }

    private void setShardStatus(long shardId, String status) {
        plainJdbc.update("update ana_migration_shard set status = ? where shard_id = ?", status, shardId);
    }

    private Long shardId(long commandId, int shardSeq) {
        return plainJdbc.queryForObject("""
                select shard_id
                from ana_migration_shard
                where command_id = ? and shard_seq = ?
                """, Long.class, commandId, shardSeq);
    }
}
