package com.spdb.migration;

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;

import java.lang.reflect.Constructor;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.RejectedExecutionException;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

class MigrationBatchRunnerTest {
    private NamedParameterJdbcTemplate jdbc;
    private JdbcTemplate plainJdbc;
    private PlatformTransactionManager transactionManager;
    private MigrationCommandService commandService;
    private MigrationShardRunner shardRunner;
    private ThreadPoolTaskExecutor executor;
    private MigrationBatchRunner batchRunner;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:migration_batch;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        jdbc = new NamedParameterJdbcTemplate(dataSource);
        plainJdbc = new JdbcTemplate(dataSource);
        transactionManager = new DataSourceTransactionManager(dataSource);
        plainJdbc.execute("drop table if exists ana_migration_shard");
        plainJdbc.execute("drop table if exists ana_migration_command");
        plainJdbc.execute("""
                create table ana_migration_command (
                    command_id bigint generated by default as identity primary key,
                    source_data_source varchar(64) not null,
                    target_data_source varchar(64) not null,
                    command_type varchar(32) not null default 'TIME_RANGE',
                    time_from bigint not null,
                    time_to bigint not null,
                    window_seconds bigint not null,
                    parallelism integer not null,
                    status varchar(32) not null,
                    total_shard_count bigint not null default 0,
                    completed_shard_count bigint not null default 0,
                    failed_shard_count bigint not null default 0,
                    migrated_rows bigint not null default 0,
                    skipped_rows bigint not null default 0,
                    dropped_rows bigint not null default 0,
                    request_sql clob,
                    response_sql clob,
                    tran_codes clob,
                    sample_size integer,
                    error_message varchar(2000),
                    remark varchar(1000),
                    created_by varchar(100),
                    created_time timestamp default current_timestamp,
                    started_time timestamp,
                    ended_time timestamp,
                    updated_at timestamp default current_timestamp
                )
                """);
        plainJdbc.execute("""
                create table ana_migration_shard (
                    shard_id bigint generated by default as identity primary key,
                    command_id bigint not null,
                    shard_seq integer not null,
                    tran_code varchar(32),
                    time_from bigint not null,
                    time_to bigint not null,
                    status varchar(32) not null,
                    migrated_rows bigint not null default 0,
                    skipped_rows bigint not null default 0,
                    dropped_rows bigint not null default 0,
                    error_message varchar(2000),
                    attempts integer not null default 0,
                    created_time timestamp default current_timestamp,
                    started_time timestamp,
                    ended_time timestamp,
                    updated_at timestamp default current_timestamp
                )
                """);
        ObjectProvider<MigrationTaskLauncher> launcherProvider = launcherProvider();
        when(launcherProvider.getIfAvailable()).thenReturn(null);
        commandService = new MigrationCommandService(
                jdbc,
                transactionManager,
                launcherProvider,
                new MigrationRuntimeProperties("bxds", "primary")
        );
        shardRunner = mock(MigrationShardRunner.class);
        executor = new ThreadPoolTaskExecutor();
        executor.setThreadNamePrefix("test-migration-exec-");
        executor.setCorePoolSize(1);
        executor.setMaxPoolSize(4);
        executor.setQueueCapacity(16);
        executor.initialize();
        batchRunner = new MigrationBatchRunner(commandService, shardRunner, executor);
    }

    @AfterEach
    void tearDown() {
        if (executor != null) {
            executor.shutdown();
        }
    }

    @SuppressWarnings("unchecked")
    private ObjectProvider<MigrationTaskLauncher> launcherProvider() {
        return mock(ObjectProvider.class);
    }

    @Test
    void runCompletesRunnableShardsAndAggregatesCounters() {
        long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 250_000L, 50L, 2, "complete"));
        List<Long> shardIds = shardIds(commandId);
        when(shardRunner.run(shardIds.get(0), 100_000L, 150_000L, 1000)).thenReturn(new MigrationShardResult(10L, 1L, 0L));
        when(shardRunner.run(shardIds.get(1), 150_000L, 200_000L, 1000)).thenReturn(new MigrationShardResult(20L, 2L, 1L));
        when(shardRunner.run(shardIds.get(2), 200_000L, 250_000L, 1000)).thenReturn(new MigrationShardResult(30L, 3L, 2L));

        batchRunner.run(commandId);

        MigrationProgressRow progress = commandService.progress(commandId);
        assertThat(progress.status()).isEqualTo("COMPLETED");
        assertThat(progress.completedShardCount()).isEqualTo(3L);
        assertThat(progress.failedShardCount()).isZero();
        assertThat(progress.migratedRows()).isEqualTo(60L);
        assertThat(progress.skippedRows()).isEqualTo(6L);
        assertThat(progress.droppedRows()).isEqualTo(3L);
        assertThat(progress.shards()).extracting(MigrationShardRow::status).containsOnly("COMPLETED");
        assertThat(progress.shards()).extracting(MigrationShardRow::attempts).containsOnly(1);
    }

    @Test
    void runSqlCommandUsesSqlShardExecutionPath() {
        long commandId = commandService.createSqlCommand(new MigrationSqlCommandForm(
                "select source_ip, trans_id, txn_code, response_time, message_type, response_message, return_code, return_msg from msg_flow_log_response",
                "sql command"
        ));
        Long shardId = shardIds(commandId).get(0);
        when(shardRunner.runSql(
                shardId,
                "select source_ip, trans_id, txn_code, response_time, message_type, response_message, return_code, return_msg from msg_flow_log_response",
                1000
        )).thenReturn(new MigrationShardResult(7L, 2L, 1L));

        batchRunner.run(commandId);

        MigrationProgressRow progress = commandService.progress(commandId);
        assertThat(progress.status()).isEqualTo("COMPLETED");
        assertThat(progress.migratedRows()).isEqualTo(7L);
        assertThat(progress.skippedRows()).isEqualTo(2L);
        assertThat(progress.droppedRows()).isEqualTo(1L);
        verify(shardRunner).runSql(
                shardId,
                "select source_ip, trans_id, txn_code, response_time, message_type, response_message, return_code, return_msg from msg_flow_log_response",
                1000
        );
        verify(shardRunner, never()).run(shardId, 0L, 0L, 1000);
    }

    @Test
    void runTranCodeCommandUsesTranCodeExecutionPathAndSkipsEmptyResult() {
        long commandId = commandService.createTranCodeCommand(new MigrationTranCodeCommandForm(
                "TRAN001", 3, 1, "tran code command"
        ));
        Long shardId = shardIds(commandId).get(0);
        when(shardRunner.runTranCode(shardId, "TRAN001", 3))
                .thenReturn(new MigrationShardResult(0L, 0L, 0L));

        batchRunner.run(commandId);

        MigrationProgressRow progress = commandService.progress(commandId);
        assertThat(progress.status()).isEqualTo("COMPLETED");
        assertThat(progress.completedShardCount()).isEqualTo(1L);
        assertThat(progress.shards()).extracting(MigrationShardRow::status).containsExactly("SKIPPED");
        verify(shardRunner).runTranCode(shardId, "TRAN001", 3);
        verify(shardRunner, never()).run(anyLong(), anyLong(), anyLong(), anyInt());
        verify(shardRunner, never()).runSql(anyLong(), org.mockito.ArgumentMatchers.anyString(), anyInt());
    }

    @Test
    void runMarksCancelRequestedCommandCancelledWithoutRunningShards() {
        long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 200_000L, 50L, 2, "cancel"));
        commandService.requestCancel(commandId);

        batchRunner.run(commandId);

        MigrationProgressRow progress = commandService.progress(commandId);
        assertThat(progress.status()).isEqualTo("CANCELLED");
        assertThat(progress.completedShardCount()).isZero();
        verify(shardRunner, never()).run(anyLong(), anyLong(), anyLong(), anyInt());
    }

    @Test
    void runMarksCancelledWhenCancelArrivesBeforeMarkRunning() {
        long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 150_000L, 50L, 1, "cancel before running"));
        MigrationCommandService service = new CancelBeforeMarkRunningService();
        MigrationBatchRunner runner = new MigrationBatchRunner(service, shardRunner, executor);

        runner.run(commandId);

        MigrationProgressRow progress = commandService.progress(commandId);
        assertThat(progress.status()).isEqualTo("CANCELLED");
        assertThat(progress.completedShardCount()).isZero();
        verify(shardRunner, never()).run(anyLong(), anyLong(), anyLong(), anyInt());
    }

    @Test
    void runStopsSchedulingNewShardsWhenCancelIsRequested() {
        long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 250_000L, 50L, 1, "cancel during run"));
        List<Long> shardIds = shardIds(commandId);
        doAnswer(invocation -> {
            commandService.requestCancel(commandId);
            return new MigrationShardResult(10L, 0L, 0L);
        }).when(shardRunner).run(shardIds.get(0), 100_000L, 150_000L, 1000);

        batchRunner.run(commandId);

        MigrationProgressRow progress = commandService.progress(commandId);
        assertThat(progress.status()).isEqualTo("CANCELLED");
        assertThat(progress.completedShardCount()).isEqualTo(1L);
        assertThat(progress.shards()).extracting(MigrationShardRow::status)
                .containsExactly("COMPLETED", "PENDING", "PENDING");
        verify(shardRunner, never()).run(shardIds.get(1), 150_000L, 200_000L, 1000);
        verify(shardRunner, never()).run(shardIds.get(2), 200_000L, 250_000L, 1000);
    }

    @Test
    void runMarksCommandFailedWhenAnyShardFails() {
        long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 200_000L, 50L, 2, "failure"));
        List<Long> shardIds = shardIds(commandId);
        when(shardRunner.run(shardIds.get(0), 100_000L, 150_000L, 1000)).thenReturn(new MigrationShardResult(10L, 0L, 0L));
        when(shardRunner.run(shardIds.get(1), 150_000L, 200_000L, 1000)).thenThrow(new IllegalStateException("source unavailable"));

        batchRunner.run(commandId);

        MigrationProgressRow progress = commandService.progress(commandId);
        assertThat(progress.status()).isEqualTo("FAILED");
        assertThat(progress.completedShardCount()).isEqualTo(1L);
        assertThat(progress.failedShardCount()).isEqualTo(1L);
        assertThat(progress.migratedRows()).isEqualTo(10L);
        assertThat(progress.errorMessage()).contains("1 migration shard(s) failed");
        assertThat(progress.shards()).extracting(MigrationShardRow::status)
                .containsExactly("COMPLETED", "FAILED");
        assertThat(progress.shards().get(1).errorMessage()).contains("source unavailable");
    }

    @Test
    void finishMarksCancelledWhenCancelArrivesBeforeCompletedTransition() {
        MigrationCommandService service = new CancelBeforeMarkCompletedService();
        MigrationBatchRunner runner = new MigrationBatchRunner(service, shardRunner, executor);
        long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 150_000L, 50L, 1, "cancel before complete"));
        List<Long> shardIds = shardIds(commandId);
        when(shardRunner.run(shardIds.get(0), 100_000L, 150_000L, 1000)).thenReturn(new MigrationShardResult(10L, 0L, 0L));

        runner.run(commandId);

        MigrationProgressRow progress = commandService.progress(commandId);
        assertThat(progress.status()).isEqualTo("CANCELLED");
        assertThat(progress.completedShardCount()).isEqualTo(1L);
        assertThat(progress.shards()).extracting(MigrationShardRow::status).containsExactly("COMPLETED");
    }

    @Test
    void finishMarksCancelledWhenCancelArrivesBeforeFailedTransition() {
        MigrationCommandService service = new CancelBeforeMarkFailedService();
        MigrationBatchRunner runner = new MigrationBatchRunner(service, shardRunner, executor);
        long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 150_000L, 50L, 1, "cancel before fail"));
        List<Long> shardIds = shardIds(commandId);
        when(shardRunner.run(shardIds.get(0), 100_000L, 150_000L, 1000)).thenThrow(new IllegalStateException("source unavailable"));

        runner.run(commandId);

        MigrationProgressRow progress = commandService.progress(commandId);
        assertThat(progress.status()).isEqualTo("CANCELLED");
        assertThat(progress.failedShardCount()).isEqualTo(1L);
        assertThat(progress.shards()).extracting(MigrationShardRow::status).containsExactly("FAILED");
    }

    @Test
    void runThrowsWhenCommandIsMissing() {
        assertThatThrownBy(() -> batchRunner.run(999999L))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("Migration command not found");
    }

    @Test
    void asyncExecutorUsesCommandExecutorAndBatchRunnerUsesShardExecutor() throws Exception {
        ThreadPoolTaskExecutor shardExecutor = executor("test-migration-shard-", 1, 1, 16);
        List<String> threadNames = new ArrayList<>();
        try {
            Constructor<MigrationAsyncExecutor> asyncConstructor = MigrationAsyncExecutor.class.getConstructor(
                    ObjectProvider.class,
                    ThreadPoolTaskExecutor.class
            );
            Qualifier asyncExecutorQualifier = asyncConstructor.getParameters()[1].getAnnotation(Qualifier.class);
            Constructor<MigrationBatchRunner> batchConstructor = MigrationBatchRunner.class.getConstructor(
                    MigrationCommandService.class,
                    MigrationShardRunner.class,
                    ThreadPoolTaskExecutor.class
            );
            Qualifier shardExecutorQualifier = batchConstructor.getParameters()[2].getAnnotation(Qualifier.class);
            long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 150_000L, 50L, 1, "executor split"));
            List<Long> shardIds = shardIds(commandId);
            when(shardRunner.run(shardIds.get(0), 100_000L, 150_000L, 1000)).thenAnswer(invocation -> {
                threadNames.add(Thread.currentThread().getName());
                return new MigrationShardResult(1L, 0L, 0L);
            });
            MigrationBatchRunner runner = new MigrationBatchRunner(commandService, shardRunner, shardExecutor);

            runner.run(commandId);

            assertThat(asyncExecutorQualifier.value()).isEqualTo("migrationCommandTaskExecutor");
            assertThat(shardExecutorQualifier.value()).isEqualTo("migrationTaskExecutor");
            assertThat(threadNames).anyMatch(name -> name.startsWith("test-migration-shard-"));
        } finally {
            shardExecutor.shutdown();
        }
    }

    @Test
    void runDoesNotScheduleShardsWhenCommandCannotTransitionToRunning() {
        long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 150_000L, 50L, 1, "stale"));
        plainJdbc.update("update ana_migration_command set status = 'RUNNING' where command_id = ?", commandId);

        batchRunner.run(commandId);

        assertThat(commandService.progress(commandId).status()).isEqualTo("RUNNING");
        assertThat(commandService.progress(commandId).shards()).extracting(MigrationShardRow::status)
                .containsExactly("PENDING");
        verify(shardRunner, never()).run(anyLong(), anyLong(), anyLong(), anyInt());
    }

    @Test
    void queuedShardDoesNotStartAfterCancelRequested() {
        ThreadPoolTaskExecutor shardExecutor = executor("test-migration-queued-", 1, 1, 16);
        try {
            MigrationBatchRunner runner = new MigrationBatchRunner(commandService, shardRunner, shardExecutor);
            long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 200_000L, 50L, 2, "queued cancel"));
            List<Long> shardIds = shardIds(commandId);
            doAnswer(invocation -> {
                commandService.requestCancel(commandId);
                return new MigrationShardResult(10L, 0L, 0L);
            }).when(shardRunner).run(shardIds.get(0), 100_000L, 150_000L, 1000);

            runner.run(commandId);

            MigrationProgressRow progress = commandService.progress(commandId);
            assertThat(progress.status()).isEqualTo("CANCELLED");
            assertThat(progress.shards()).extracting(MigrationShardRow::status)
                    .containsExactly("COMPLETED", "PENDING");
            verify(shardRunner, never()).run(shardIds.get(1), 150_000L, 200_000L, 1000);
        } finally {
            shardExecutor.shutdown();
        }
    }

    @Test
    void runMarksCommandFailedWhenShardSchedulingFails() {
        ThreadPoolTaskExecutor rejectingExecutor = mock(ThreadPoolTaskExecutor.class);
        when(rejectingExecutor.getThreadNamePrefix()).thenReturn("rejecting-");
        doAnswer(invocation -> {
            throw new RejectedExecutionException("queue full");
        }).when(rejectingExecutor).execute(org.mockito.ArgumentMatchers.any(Runnable.class));
        MigrationBatchRunner runner = new MigrationBatchRunner(commandService, shardRunner, rejectingExecutor);
        long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 150_000L, 50L, 1, "reject"));

        runner.run(commandId);

        MigrationProgressRow progress = commandService.progress(commandId);
        assertThat(progress.status()).isEqualTo("FAILED");
        assertThat(progress.errorMessage()).contains("queue full");
        verify(shardRunner, never()).run(anyLong(), anyLong(), anyLong(), anyInt());
    }

    @Test
    void commandLevelFailureMarksCancelledWhenCancelWinsFailureRace() {
        ThreadPoolTaskExecutor rejectingExecutor = mock(ThreadPoolTaskExecutor.class);
        doAnswer(invocation -> {
            throw new RejectedExecutionException("queue full");
        }).when(rejectingExecutor).execute(org.mockito.ArgumentMatchers.any(Runnable.class));
        MigrationCommandService racingCommandService = new MigrationCommandService(
                jdbc,
                new DataSourceTransactionManager(plainJdbc.getDataSource()),
                launcherProvider(),
                new MigrationRuntimeProperties("bxds", "primary")
        ) {
            @Override
            boolean markFailed(long commandId, String errorMessage) {
                requestCancel(commandId);
                return super.markFailed(commandId, errorMessage);
            }
        };
        MigrationBatchRunner runner = new MigrationBatchRunner(racingCommandService, shardRunner, rejectingExecutor);
        long commandId = racingCommandService.createCommand(new MigrationCommandForm(100_000L, 150_000L, 50L, 1, "cancel failure race"));

        runner.run(commandId);

        assertThat(racingCommandService.progress(commandId).status()).isEqualTo("CANCELLED");
    }

    private ThreadPoolTaskExecutor executor(String threadNamePrefix, int corePoolSize, int maxPoolSize, int queueCapacity) {
        ThreadPoolTaskExecutor taskExecutor = new ThreadPoolTaskExecutor();
        taskExecutor.setThreadNamePrefix(threadNamePrefix);
        taskExecutor.setCorePoolSize(corePoolSize);
        taskExecutor.setMaxPoolSize(maxPoolSize);
        taskExecutor.setQueueCapacity(queueCapacity);
        taskExecutor.initialize();
        return taskExecutor;
    }

    private class CancelBeforeMarkRunningService extends MigrationCommandService {
        CancelBeforeMarkRunningService() {
            super(jdbc, transactionManager, launcherProvider(), new MigrationRuntimeProperties("bxds", "primary"));
        }

        @Override
        boolean markRunning(long commandId) {
            requestCancel(commandId);
            return super.markRunning(commandId);
        }
    }

    private class CancelBeforeMarkCompletedService extends MigrationCommandService {
        CancelBeforeMarkCompletedService() {
            super(jdbc, transactionManager, launcherProvider(), new MigrationRuntimeProperties("bxds", "primary"));
        }

        @Override
        boolean markCompleted(long commandId) {
            requestCancel(commandId);
            return super.markCompleted(commandId);
        }
    }

    private class CancelBeforeMarkFailedService extends MigrationCommandService {
        CancelBeforeMarkFailedService() {
            super(jdbc, transactionManager, launcherProvider(), new MigrationRuntimeProperties("bxds", "primary"));
        }

        @Override
        boolean markFailed(long commandId, String errorMessage) {
            requestCancel(commandId);
            return super.markFailed(commandId, errorMessage);
        }
    }

    private List<Long> shardIds(long commandId) {
        return plainJdbc.queryForList("""
                select shard_id
                from ana_migration_shard
                where command_id = ?
                order by shard_seq
                """, Long.class, commandId);
    }
}
