package com.spdb.migration;

import com.spdb.web.PageRequestParams;
import com.spdb.web.PagedResult;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.reset;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

class MigrationCommandServiceTest {
    private NamedParameterJdbcTemplate jdbc;
    private JdbcTemplate plainJdbc;
    private MigrationCommandService service;
    private MigrationTaskLauncher launcher;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:migration_command;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        jdbc = new NamedParameterJdbcTemplate(dataSource);
        plainJdbc = new JdbcTemplate(dataSource);
        plainJdbc.execute("drop table if exists ana_migration_shard");
        plainJdbc.execute("drop table if exists ana_migration_command");
        plainJdbc.execute("""
                create table ana_migration_command (
                    command_id bigint generated by default as identity primary key,
                    source_data_source varchar(64) not null,
                    target_data_source varchar(64) not null,
                    command_type varchar(32) not null default 'TIME_RANGE',
                    time_from bigint not null,
                    time_to bigint not null,
                    window_seconds bigint not null,
                    parallelism integer not null,
                    status varchar(32) not null,
                    total_shard_count bigint not null default 0,
                    completed_shard_count bigint not null default 0,
                    failed_shard_count bigint not null default 0,
                    migrated_rows bigint not null default 0,
                    skipped_rows bigint not null default 0,
                    dropped_rows bigint not null default 0,
                    request_sql clob,
                    response_sql clob,
                    tran_codes clob,
                    sample_size integer,
                    error_message varchar(2000),
                    remark varchar(1000),
                    created_by varchar(100),
                    created_time timestamp default current_timestamp,
                    started_time timestamp,
                    ended_time timestamp,
                    updated_at timestamp default current_timestamp
                )
                """);
        plainJdbc.execute("""
                create table ana_migration_shard (
                    shard_id bigint generated by default as identity primary key,
                    command_id bigint not null,
                    shard_seq integer not null,
                    tran_code varchar(32),
                    time_from bigint not null,
                    time_to bigint not null,
                    status varchar(32) not null,
                    migrated_rows bigint not null default 0,
                    skipped_rows bigint not null default 0,
                    dropped_rows bigint not null default 0,
                    error_message varchar(2000),
                    attempts integer not null default 0,
                    created_time timestamp default current_timestamp,
                    started_time timestamp,
                    ended_time timestamp,
                    updated_at timestamp default current_timestamp
                )
                """);
        launcher = mock(MigrationTaskLauncher.class);
        ObjectProvider<MigrationTaskLauncher> provider = launcherProvider();
        when(provider.getIfAvailable()).thenReturn(launcher);
        service = new MigrationCommandService(
                jdbc,
                new DataSourceTransactionManager(dataSource),
                provider,
                new MigrationRuntimeProperties("bxds", "primary")
        );
    }

    @SuppressWarnings("unchecked")
    private ObjectProvider<MigrationTaskLauncher> launcherProvider() {
        return mock(ObjectProvider.class);
    }

    @Test
    void createCommandSplitsHalfOpenWindowsAndLaunches() {
        long commandId = service.createCommand(new MigrationCommandForm(100_000L, 250_000L, 60L, 2, "demo"));

        assertThat(commandId).isPositive();
        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_shard where command_id = " + commandId, Long.class))
                .isEqualTo(3L);
        assertThat(plainJdbc.queryForList("select time_from from ana_migration_shard where command_id = " + commandId + " order by shard_seq", Long.class))
                .containsExactly(100_000L, 160_000L, 220_000L);
        assertThat(plainJdbc.queryForList("select time_to from ana_migration_shard where command_id = " + commandId + " order by shard_seq", Long.class))
                .containsExactly(160_000L, 220_000L, 250_000L);
        verify(launcher).launch(commandId);
    }

    @Test
    void createSqlCommandStoresSqlAndCreatesSingleShard() {
        MigrationSqlCommandForm form = new MigrationSqlCommandForm(
                "select source_ip, trans_id, txn_code, response_time, message_type, response_message, return_code, return_msg from msg_flow_log_response where txn_code = 'PAY001'",
                "sql migration"
        );

        long commandId = service.createSqlCommand(form);

        assertThat(commandId).isPositive();
        MapRow row = plainJdbc.queryForObject("""
                select command_type, request_sql, response_sql, time_from, time_to, window_seconds, parallelism, total_shard_count, remark
                from ana_migration_command
                where command_id = ?
                """, (rs, i) -> new MapRow(
                rs.getString("command_type"),
                rs.getString("request_sql"),
                rs.getString("response_sql"),
                rs.getLong("time_from"),
                rs.getLong("time_to"),
                rs.getLong("window_seconds"),
                rs.getInt("parallelism"),
                rs.getLong("total_shard_count"),
                rs.getString("remark")
        ), commandId);
        assertThat(row.commandType()).isEqualTo("SQL");
        assertThat(row.requestSql()).isNull();
        assertThat(row.responseSql()).contains("from msg_flow_log_response");
        assertThat(row.timeFrom()).isZero();
        assertThat(row.timeTo()).isZero();
        assertThat(row.windowSeconds()).isZero();
        assertThat(row.parallelism()).isEqualTo(1);
        assertThat(row.totalShardCount()).isEqualTo(1L);
        assertThat(row.remark()).isEqualTo("sql migration");
        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_shard where command_id = " + commandId, Long.class))
                .isEqualTo(1L);
        verify(launcher).launch(commandId);
    }

    @Test
    void createTranCodeCommandDeduplicatesCodesCreatesShardsAndLaunches() {
        long commandId = service.createTranCodeCommand(new MigrationTranCodeCommandForm(
                "A001, B002, A001", 3, 2, "tran code migration"
        ));

        assertThat(commandId).isPositive();
        TranCodeCommandRow command = plainJdbc.queryForObject("""
                select command_type, tran_codes, sample_size, parallelism, total_shard_count, remark
                from ana_migration_command
                where command_id = ?
                """, (rs, i) -> new TranCodeCommandRow(
                rs.getString("command_type"),
                rs.getString("tran_codes"),
                rs.getInt("sample_size"),
                rs.getInt("parallelism"),
                rs.getLong("total_shard_count"),
                rs.getString("remark")
        ), commandId);
        assertThat(command).isEqualTo(new TranCodeCommandRow(
                "TRAN_CODE", "A001,B002", 3, 2, 2L, "tran code migration"
        ));
        assertThat(plainJdbc.queryForList("""
                select tran_code
                from ana_migration_shard
                where command_id = %d
                order by shard_seq
                """.formatted(commandId), String.class)).containsExactly("A001", "B002");
        verify(launcher).launch(commandId);
    }

    @Test
    void createTranCodeCommandRejectsInvalidForms() {
        assertThatThrownBy(() -> service.createTranCodeCommand(new MigrationTranCodeCommandForm("", 3, 2, "")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createTranCodeCommand(new MigrationTranCodeCommandForm(" ,  ", 3, 2, "")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createTranCodeCommand(new MigrationTranCodeCommandForm("A001", 0, 2, "")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createTranCodeCommand(new MigrationTranCodeCommandForm("A001", -1, 2, "")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createTranCodeCommand(new MigrationTranCodeCommandForm("A001", 3, 9, "")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createTranCodeCommand(new MigrationTranCodeCommandForm("A".repeat(33), 3, 2, "")))
                .isInstanceOf(IllegalArgumentException.class);

        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_command", Long.class)).isZero();
        verify(launcher, never()).launch(1L);
    }

    @Test
    void createTranCodeCommandRollsBackWhenShardInsertFails() {
        plainJdbc.execute("alter table ana_migration_shard add constraint ck_test_tran_code check (tran_code <> 'B002')");

        assertThatThrownBy(() -> service.createTranCodeCommand(new MigrationTranCodeCommandForm(
                "A001,B002", 3, 2, "rollback"
        ))).isInstanceOf(RuntimeException.class);

        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_command", Long.class)).isZero();
        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_shard", Long.class)).isZero();
        verifyNoInteractions(launcher);
    }

    @Test
    void searchTranCodeReturnsOnlyTranCodeCommandsWithPageMetadata() {
        for (int index = 0; index < 21; index++) {
            service.createTranCodeCommand(new MigrationTranCodeCommandForm(
                    "T%03d".formatted(index), 3, 2, "transaction code " + index
            ));
        }
        service.createCommand(new MigrationCommandForm(100_000L, 160_000L, 60L, 2, "time range"));
        service.createSqlCommand(new MigrationSqlCommandForm("select source_ip from msg_flow_log_response", "sql"));

        PagedResult<MigrationCommandRow> result = service.searchTranCode(PageRequestParams.of(2, 20));

        assertThat(result.total()).isEqualTo(21L);
        assertThat(result.page()).isEqualTo(2);
        assertThat(result.size()).isEqualTo(20);
        assertThat(result.totalPages()).isEqualTo(2);
        assertThat(result.rows()).hasSize(1);
        assertThat(result.rows().get(0).commandType()).isEqualTo("TRAN_CODE");
    }

    @Test
    void createSqlCommandRejectsMissingAndUnsafeSql() {
        assertThatThrownBy(() -> service.createSqlCommand(null))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("SQL迁移指令参数不能为空");
        assertThatThrownBy(() -> service.createSqlCommand(new MigrationSqlCommandForm("", "")))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("Response SQL不能为空");
        assertThatThrownBy(() -> service.createSqlCommand(new MigrationSqlCommandForm(
                "select * from msg_flow_log_response; delete from msg_flow_log_response",
                "bad"
        ))).isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("只允许单条查询SQL");
        assertThatThrownBy(() -> service.createSqlCommand(new MigrationSqlCommandForm(
                "update msg_flow_log_response set txn_code = 'X'",
                "bad"
        ))).isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("只允许select或with查询");

        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_command", Long.class))
                .isZero();
        verify(launcher, never()).launch(1L);
    }

    @Test
    void createCommandRejectsInvalidForms() {
        assertThatThrownBy(() -> service.createCommand(null))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(200_000L, 200_000L, 60L, 2, "demo")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(200_000L, 199_000L, 60L, 2, "demo")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(100_000L, 200_000L, 0L, 2, "demo")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(100_000L, 200_000L, 60L, 0, "demo")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(100_000L, 200_000L, 60L, 9, "demo")))
                .isInstanceOf(IllegalArgumentException.class)
                .hasMessageContaining("并行度");
    }

    private record TranCodeCommandRow(
            String commandType,
            String tranCodes,
            int sampleSize,
            int parallelism,
            long totalShardCount,
            String remark
    ) {
    }

    @Test
    void createCommandRollsBackCommandWhenShardInsertFails() {
        plainJdbc.execute("alter table ana_migration_shard add constraint ck_test_shard_time_to check (time_to < 200000)");

        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(100_000L, 220_000L, 60L, 2, "rollback")))
                .isInstanceOf(RuntimeException.class);

        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_command", Long.class))
                .isZero();
        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_shard", Long.class))
                .isZero();
        verify(launcher, never()).launch(1L);
    }

    @Test
    void createCommandRejectsExcessiveAndOverflowingShardRangesBeforeInsert() {
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(0L, 10_001_000L, 1L, 2, "too many")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(0L, Long.MAX_VALUE, Long.MAX_VALUE - 1L, 2, "overflow count")))
                .isInstanceOf(IllegalArgumentException.class);
        assertThatThrownBy(() -> service.createCommand(new MigrationCommandForm(Long.MAX_VALUE - 2L, Long.MAX_VALUE, Long.MAX_VALUE, 2, "overflow window")))
                .isInstanceOf(IllegalArgumentException.class);

        assertThat(plainJdbc.queryForObject("select count(*) from ana_migration_command", Long.class))
                .isZero();
        verify(launcher, never()).launch(1L);
    }

    @Test
    void searchReturnsCommandRowsAndPageMetadata() {
        long firstCommandId = service.createCommand(new MigrationCommandForm(100_000L, 220_000L, 60L, 2, "first"));
        long secondCommandId = service.createCommand(new MigrationCommandForm(300_000L, 420_000L, 60L, 4, "second"));

        PagedResult<MigrationCommandRow> result = service.search(PageRequestParams.of(1, 20));

        assertThat(result.total()).isEqualTo(2);
        assertThat(result.page()).isEqualTo(1);
        assertThat(result.size()).isEqualTo(20);
        assertThat(result.totalPages()).isEqualTo(1);
        assertThat(result.rows()).hasSize(2);
        assertThat(result.rows()).extracting(MigrationCommandRow::commandId)
                .containsExactly(secondCommandId, firstCommandId);
        assertThat(result.rows()).extracting(MigrationCommandRow::sourceDataSource)
                .containsOnly("bxds");
        assertThat(result.rows()).extracting(MigrationCommandRow::targetDataSource)
                .containsOnly("primary");
        assertThat(result.rows()).extracting(MigrationCommandRow::status)
                .containsOnly("CREATED");
        assertThat(result.rows()).extracting(MigrationCommandRow::totalShardCount)
                .containsExactly(2L, 2L);
    }

    @Test
    void searchClampsOutOfRangePageBeforeQueryingRows() {
        for (int i = 0; i < 21; i++) {
            long timeFrom = 100_000L + (i * 100_000L);
            service.createCommand(new MigrationCommandForm(timeFrom, timeFrom + 60_000L, 60L, 2, "command-" + i));
        }

        PagedResult<MigrationCommandRow> result = service.search(PageRequestParams.of(999, 20));

        assertThat(result.total()).isEqualTo(21);
        assertThat(result.totalPages()).isEqualTo(2);
        assertThat(result.page()).isEqualTo(2);
        assertThat(result.rows()).hasSize(1);
        assertThat(result.rows().get(0).sourceDataSource()).isEqualTo("bxds");
        assertThat(result.rows().get(0).targetDataSource()).isEqualTo("primary");
    }

    @Test
    void progressReturnsCommandAndShardRows() {
        long commandId = service.createCommand(new MigrationCommandForm(100_000L, 220_000L, 60L, 2, "demo"));

        MigrationProgressRow progress = service.progress(commandId);

        assertThat(progress.commandId()).isEqualTo(commandId);
        assertThat(progress.sourceDataSource()).isEqualTo("bxds");
        assertThat(progress.targetDataSource()).isEqualTo("primary");
        assertThat(progress.totalShardCount()).isEqualTo(2);
        assertThat(progress.shards()).hasSize(2);
    }

    @Test
    void cancelAndResumeUpdateCommandStatus() {
        long commandId = service.createCommand(new MigrationCommandForm(100_000L, 220_000L, 60L, 2, "demo"));
        reset(launcher);

        service.requestCancel(commandId);
        assertThat(service.progress(commandId).status()).isEqualTo("CANCEL_REQUESTED");

        service.resume(commandId);
        assertThat(service.progress(commandId).status()).isEqualTo("CREATED");
        verify(launcher).launch(commandId);
    }

    @Test
    void resumeDoesNotLaunchWhenStatusCannotBeResumed() {
        long createdCommandId = service.createCommand(new MigrationCommandForm(100_000L, 160_000L, 60L, 2, "created"));
        long completedCommandId = service.createCommand(new MigrationCommandForm(300_000L, 360_000L, 60L, 2, "completed"));
        setCommandStatus(completedCommandId, "COMPLETED");
        reset(launcher);

        service.resume(createdCommandId);
        service.resume(completedCommandId);
        service.resume(999999L);

        verify(launcher, never()).launch(createdCommandId);
        verify(launcher, never()).launch(completedCommandId);
        verify(launcher, never()).launch(999999L);
    }

    @Test
    void resumeRecoversStaleRunningCommandAndRunningShards() {
        long commandId = service.createCommand(new MigrationCommandForm(100_000L, 220_000L, 60L, 2, "stale running"));
        Long firstShardId = shardId(commandId, 0);
        Long secondShardId = shardId(commandId, 1);
        setCommandStatus(commandId, "RUNNING");
        setShardStatus(firstShardId, "RUNNING");
        setShardStatus(secondShardId, "COMPLETED");
        reset(launcher);

        service.resume(commandId);

        assertThat(service.progress(commandId).status()).isEqualTo("CREATED");
        assertThat(service.shard(firstShardId).status()).isEqualTo("FAILED");
        assertThat(service.shard(firstShardId).errorMessage()).contains("stale running shard reset for resume");
        assertThat(service.shard(secondShardId).status()).isEqualTo("COMPLETED");
        verify(launcher).launch(commandId);
    }

    @Test
    void terminalCommandHelpersUseStatusGuards() {
        long completedCommandId = service.createCommand(new MigrationCommandForm(100_000L, 160_000L, 60L, 2, "complete"));
        reset(launcher);

        service.markCompleted(completedCommandId);
        assertThat(service.progress(completedCommandId).status()).isEqualTo("CREATED");

        service.markRunning(completedCommandId);
        service.markCompleted(completedCommandId);
        assertThat(service.progress(completedCommandId).status()).isEqualTo("COMPLETED");

        service.markFailed(completedCommandId, "late failure");
        service.markCancelled(completedCommandId);
        assertThat(service.progress(completedCommandId).status()).isEqualTo("COMPLETED");

        long failedCommandId = service.createCommand(new MigrationCommandForm(200_000L, 260_000L, 60L, 2, "fail"));
        service.markRunning(failedCommandId);
        service.markFailed(failedCommandId, "failed");
        assertThat(service.progress(failedCommandId).status()).isEqualTo("FAILED");

        service.markCompleted(failedCommandId);
        service.markCancelled(failedCommandId);
        assertThat(service.progress(failedCommandId).status()).isEqualTo("FAILED");

        long createdCommandId = service.createCommand(new MigrationCommandForm(300_000L, 360_000L, 60L, 2, "created"));
        service.markCancelled(createdCommandId);
        assertThat(service.progress(createdCommandId).status()).isEqualTo("CANCELLED");

        long cancelRequestedCommandId = service.createCommand(new MigrationCommandForm(400_000L, 460_000L, 60L, 2, "cancel"));
        service.requestCancel(cancelRequestedCommandId);
        service.markCancelled(cancelRequestedCommandId);
        assertThat(service.progress(cancelRequestedCommandId).status()).isEqualTo("CANCELLED");
    }

    @Test
    void runnerFacingHelpersUpdateShardAndCommandState() {
        long commandId = service.createCommand(new MigrationCommandForm(100_000L, 220_000L, 60L, 2, "demo"));
        reset(launcher);
        Long firstShardId = shardId(commandId, 0);
        Long secondShardId = shardId(commandId, 1);

        service.markRunning(commandId);
        assertThat(service.progress(commandId).status()).isEqualTo("RUNNING");
        assertThat(service.tryStartShard(firstShardId)).isTrue();
        assertThat(service.tryStartShard(firstShardId)).isFalse();
        assertThat(service.shard(firstShardId).status()).isEqualTo("RUNNING");
        assertThat(service.shard(firstShardId).attempts()).isEqualTo(1);

        service.markShardCompleted(firstShardId, 10L, 2L, 1L);
        MigrationShardRow completedShard = service.shard(firstShardId);
        assertThat(completedShard.status()).isEqualTo("COMPLETED");
        assertThat(completedShard.migratedRows()).isEqualTo(10L);
        assertThat(completedShard.skippedRows()).isEqualTo(2L);
        assertThat(completedShard.droppedRows()).isEqualTo(1L);

        assertThat(service.tryStartShard(secondShardId)).isTrue();
        service.markShardFailed(secondShardId, "boom");
        assertThat(service.shard(secondShardId).status()).isEqualTo("FAILED");
        assertThat(service.shard(secondShardId).errorMessage()).isEqualTo("boom");

        service.refreshCommandCounters(commandId);
        MigrationProgressRow progress = service.progress(commandId);
        assertThat(progress.completedShardCount()).isEqualTo(1L);
        assertThat(progress.failedShardCount()).isEqualTo(1L);
        assertThat(progress.migratedRows()).isEqualTo(10L);
        assertThat(progress.skippedRows()).isEqualTo(2L);
        assertThat(progress.droppedRows()).isEqualTo(1L);

        assertThat(service.isCancelRequested(commandId)).isFalse();
        service.requestCancel(commandId);
        assertThat(service.isCancelRequested(commandId)).isTrue();
    }

    private void setCommandStatus(long commandId, String status) {
        plainJdbc.update("update ana_migration_command set status = ? where command_id = ?", status, commandId);
    }

    private void setShardStatus(long shardId, String status) {
        plainJdbc.update("update ana_migration_shard set status = ? where shard_id = ?", status, shardId);
    }

    private Long shardId(long commandId, int shardSeq) {
        return plainJdbc.queryForObject("""
                select shard_id
                from ana_migration_shard
                where command_id = ? and shard_seq = ?
                """, Long.class, commandId, shardSeq);
    }

    private record MapRow(
            String commandType,
            String requestSql,
            String responseSql,
            long timeFrom,
            long timeTo,
            long windowSeconds,
            int parallelism,
            long totalShardCount,
            String remark
    ) {
    }
}
