package com.spdb.migration;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;
import org.springframework.transaction.PlatformTransactionManager;

import javax.sql.DataSource;
import java.util.List;
import java.util.concurrent.RejectedExecutionException;

import static org.assertj.core.api.Assertions.assertThat;

class MigrationBatchRunnerLoggingTest {
    private NamedParameterJdbcTemplate jdbc;
    private JdbcTemplate plainJdbc;
    private PlatformTransactionManager transactionManager;
    private MigrationCommandService commandService;
    private ThreadPoolTaskExecutor executor;

    @BeforeEach
    void setUp() {
        DataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:migration_batch_logging;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        jdbc = new NamedParameterJdbcTemplate(dataSource);
        plainJdbc = new JdbcTemplate(dataSource);
        transactionManager = new DataSourceTransactionManager(dataSource);
        plainJdbc.execute("drop table if exists ana_migration_shard");
        plainJdbc.execute("drop table if exists ana_migration_command");
        plainJdbc.execute("""
                create table ana_migration_command (
                    command_id bigint generated by default as identity primary key,
                    source_data_source varchar(64) not null,
                    target_data_source varchar(64) not null,
                    command_type varchar(32) not null default 'TIME_RANGE',
                    time_from bigint not null,
                    time_to bigint not null,
                    window_seconds bigint not null,
                    parallelism integer not null,
                    status varchar(32) not null,
                    total_shard_count bigint not null default 0,
                    completed_shard_count bigint not null default 0,
                    failed_shard_count bigint not null default 0,
                    migrated_rows bigint not null default 0,
                    skipped_rows bigint not null default 0,
                    dropped_rows bigint not null default 0,
                    request_sql clob,
                    response_sql clob,
                    tran_codes clob,
                    sample_size integer,
                    error_message varchar(2000),
                    remark varchar(1000),
                    created_by varchar(100),
                    created_time timestamp default current_timestamp,
                    started_time timestamp,
                    ended_time timestamp,
                    updated_at timestamp default current_timestamp
                )
                """);
        plainJdbc.execute("""
                create table ana_migration_shard (
                    shard_id bigint generated by default as identity primary key,
                    command_id bigint not null,
                    shard_seq integer not null,
                    tran_code varchar(32),
                    time_from bigint not null,
                    time_to bigint not null,
                    status varchar(32) not null,
                    migrated_rows bigint not null default 0,
                    skipped_rows bigint not null default 0,
                    dropped_rows bigint not null default 0,
                    error_message varchar(2000),
                    attempts integer not null default 0,
                    created_time timestamp default current_timestamp,
                    started_time timestamp,
                    ended_time timestamp,
                    updated_at timestamp default current_timestamp
                )
                """);
        commandService = new MigrationCommandService(
                jdbc,
                transactionManager,
                emptyLauncherProvider(),
                new MigrationRuntimeProperties("bxds", "primary")
        );
        executor = directExecutor();
    }

    @AfterEach
    void tearDown() {
        if (executor != null) {
            executor.shutdown();
        }
    }

    @Test
    void runLogsStackTraceWhenShardFails() {
        long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 150_000L, 50L, 1, "failure log"));
        Long shardId = shardIds(commandId).get(0);
        MigrationBatchRunner runner = new MigrationBatchRunner(
                commandService,
                throwingShardRunner(new IllegalStateException("source unavailable")),
                executor
        );

        ListAppender<ILoggingEvent> appender = attachAppender();
        try {
            runner.run(commandId);
        } finally {
            detachAppender(appender);
        }

        assertThat(appender.list).anySatisfy(event -> {
            assertThat(event.getLevel()).isEqualTo(Level.ERROR);
            assertThat(event.getFormattedMessage())
                    .contains("commandId=" + commandId)
                    .contains("shardId=" + shardId);
            assertThat(event.getThrowableProxy()).isNotNull();
            assertThat(event.getThrowableProxy().getMessage()).isEqualTo("source unavailable");
        });
    }

    @Test
    void runLogsStackTraceWhenCommandLevelFailureFails() {
        ThreadPoolTaskExecutor rejectingExecutor = new RejectingExecutor();
        MigrationBatchRunner runner = new MigrationBatchRunner(
                commandService,
                throwingShardRunner(new IllegalStateException("should not run")),
                rejectingExecutor
        );
        long commandId = commandService.createCommand(new MigrationCommandForm(100_000L, 150_000L, 50L, 1, "command failure log"));

        ListAppender<ILoggingEvent> appender = attachAppender();
        try {
            runner.run(commandId);
        } finally {
            detachAppender(appender);
        }

        assertThat(appender.list).anySatisfy(event -> {
            assertThat(event.getLevel()).isEqualTo(Level.ERROR);
            assertThat(event.getFormattedMessage()).contains("commandId=" + commandId);
            assertThat(event.getThrowableProxy()).isNotNull();
            assertThat(event.getThrowableProxy().getMessage()).isEqualTo("queue full");
        });
    }

    @Test
    void runLogsStackTraceWhenFailureStatusWritebackFails() {
        MigrationCommandService failingCommandService = new RefreshFailingCommandService();
        ThreadPoolTaskExecutor rejectingExecutor = new RejectingExecutor();
        MigrationBatchRunner runner = new MigrationBatchRunner(
                failingCommandService,
                throwingShardRunner(new IllegalStateException("should not run")),
                rejectingExecutor
        );
        long commandId = failingCommandService.createCommand(new MigrationCommandForm(100_000L, 150_000L, 50L, 1, "writeback failure log"));

        ListAppender<ILoggingEvent> appender = attachAppender();
        try {
            runner.run(commandId);
        } finally {
            detachAppender(appender);
        }

        assertThat(appender.list).anySatisfy(event -> {
            assertThat(event.getLevel()).isEqualTo(Level.ERROR);
            assertThat(event.getFormattedMessage())
                    .contains("Migration command counter refresh failed")
                    .contains("commandId=" + commandId);
            assertThat(event.getThrowableProxy()).isNotNull();
            assertThat(event.getThrowableProxy().getMessage()).isEqualTo("counter table unavailable");
        });
    }

    private ObjectProvider<MigrationTaskLauncher> emptyLauncherProvider() {
        return new ObjectProvider<>() {
            @Override
            public MigrationTaskLauncher getObject(Object... args) {
                return null;
            }

            @Override
            public MigrationTaskLauncher getIfAvailable() {
                return null;
            }

            @Override
            public MigrationTaskLauncher getIfUnique() {
                return null;
            }

            @Override
            public MigrationTaskLauncher getObject() {
                return null;
            }
        };
    }

    private ThreadPoolTaskExecutor directExecutor() {
        return new ThreadPoolTaskExecutor() {
            @Override
            public void execute(Runnable task) {
                task.run();
            }
        };
    }

    private List<Long> shardIds(long commandId) {
        return plainJdbc.queryForList("""
                select shard_id
                from ana_migration_shard
                where command_id = ?
                order by shard_seq
                """, Long.class, commandId);
    }

    private ListAppender<ILoggingEvent> attachAppender() {
        Logger logger = (Logger) LoggerFactory.getLogger(MigrationBatchRunner.class);
        ListAppender<ILoggingEvent> appender = new ListAppender<>();
        appender.start();
        logger.addAppender(appender);
        return appender;
    }

    private void detachAppender(ListAppender<ILoggingEvent> appender) {
        Logger logger = (Logger) LoggerFactory.getLogger(MigrationBatchRunner.class);
        logger.detachAppender(appender);
    }

    private MigrationShardRunner throwingShardRunner(RuntimeException failure) {
        return new MigrationShardRunner(jdbc, jdbc, transactionManager) {
            @Override
            public MigrationShardResult run(long shardId, long timeFrom, long timeTo, int fetchSize) {
                throw failure;
            }
        };
    }

    private static class RejectingExecutor extends ThreadPoolTaskExecutor {
        @Override
        public void execute(Runnable task) {
            throw new RejectedExecutionException("queue full");
        }
    }

    private class RefreshFailingCommandService extends MigrationCommandService {
        private RefreshFailingCommandService() {
            super(
                    jdbc,
                    transactionManager,
                    emptyLauncherProvider(),
                    new MigrationRuntimeProperties("bxds", "primary")
            );
        }

        @Override
        void refreshCommandCounters(long commandId) {
            throw new IllegalStateException("counter table unavailable");
        }
    }
}
