package com.spdb.replay;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.support.JdbcTransactionManager;

import static org.assertj.core.api.Assertions.assertThat;

class ReplayVolumeCheckServiceTest {
    private NamedParameterJdbcTemplate jdbc;
    private ReplayVolumeCheckService service;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource ds = new DriverManagerDataSource(
                "jdbc:h2:mem:replay_volume_check;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = new NamedParameterJdbcTemplate(ds);
        jdbc.getJdbcTemplate().execute("drop table if exists ana_replay_volume_cleanup_detail");
        jdbc.getJdbcTemplate().execute("drop table if exists ana_replay_volume_check_detail");
        jdbc.getJdbcTemplate().execute("drop table if exists ana_replay_volume_check_batch");
        jdbc.getJdbcTemplate().execute("drop table if exists ana_replay_transaction_catalog");
        jdbc.getJdbcTemplate().execute("drop table if exists msg_flow_log_request");
        jdbc.getJdbcTemplate().execute("drop table if exists msg_flow_log_response");
        jdbc.getJdbcTemplate().execute("drop table if exists tp_online_service_in");
        jdbc.getJdbcTemplate().execute("drop table if exists ana_tran_code_service_mapping");
        jdbc.getJdbcTemplate().execute("create table ana_replay_transaction_catalog (tran_code varchar(200) primary key, tran_name varchar(200), business_domain varchar(200), batch_type varchar(200))");
        jdbc.getJdbcTemplate().execute("create table msg_flow_log_request (source_ip varchar(64), trans_id varchar(64), txn_code varchar(200), txn_time bigint)");
        jdbc.getJdbcTemplate().execute("create table msg_flow_log_response (source_ip varchar(64), trans_id varchar(64), txn_code varchar(200), response_time bigint)");
        jdbc.getJdbcTemplate().execute("create table tp_online_service_in (tran_code varchar(64), esf_service_code varchar(128))");
        jdbc.getJdbcTemplate().execute("create table ana_tran_code_service_mapping (mapping_id bigint generated by default as identity, tran_code varchar(32), \"528_service_code\" varchar(200), ccbs_service_code varchar(200))");
        jdbc.getJdbcTemplate().execute("create table ana_replay_volume_check_batch (check_id bigint generated by default as identity primary key, status varchar(32), catalog_snapshot_time timestamp, sample_size integer, lookback_days integer, catalog_count bigint, no_volume_count bigint, cleanup_service_count bigint, cleanup_row_count bigint, actual_cleanup_row_count bigint, migration_command_id bigint, created_time timestamp, started_time timestamp, ended_time timestamp, error_message varchar(4000))");
        jdbc.getJdbcTemplate().execute("create table ana_replay_volume_check_detail (detail_id bigint generated by default as identity primary key, check_id bigint, tran_code varchar(200), tran_name varchar(200), business_domain varchar(200), batch_type varchar(200), mapped_service_count bigint, complete_volume_count bigint, status varchar(32), migration_status varchar(32), error_message varchar(4000), created_time timestamp)");
        jdbc.getJdbcTemplate().execute("create table ana_replay_volume_cleanup_detail (cleanup_id bigint generated by default as identity primary key, check_id bigint, service_code varchar(200), mapped_tran_codes varchar(1000), catalog_hit boolean, pending_cleanup_row_count bigint, actual_cleanup_row_count bigint, status varchar(32), error_message varchar(4000), created_time timestamp, started_time timestamp, ended_time timestamp)");
        service = new ReplayVolumeCheckService(jdbc, new JdbcTransactionManager(ds));
    }

    @Test
    void splitsMessageTypesPairsCompleteRowsAndPersistsReadonlyResult() {
        jdbc.getJdbcTemplate().update("insert into ana_replay_transaction_catalog(tran_code,tran_name) values ('T001','交易一'),('T002','交易二'),('T003','交易三')");
        jdbc.getJdbcTemplate().update("insert into tp_online_service_in(tran_code,esf_service_code) values ('T001','SVC.1'),('T002','SVC.1')");
        jdbc.getJdbcTemplate().update("insert into ana_tran_code_service_mapping(tran_code,\"528_service_code\",ccbs_service_code) values ('T003','SVC2','X')");
        jdbc.getJdbcTemplate().update("insert into msg_flow_log_request values ('ip','1','SVC1&bzjson',1),('ip','2','SVC1&sop',2),('ip','3','SVC1&soap',3),('ip','4','SVC1&soap',4),('ip','5','UNKNOWN&bzjson',5)");
        jdbc.getJdbcTemplate().update("insert into msg_flow_log_response values ('ip','1','SVC1&bzjson',1),('ip','2','SVC1&sop',2),('ip','3','SVC1&soap',3),('ip','9','SVC1&soap',9),('ip','5','UNKNOWN&bzjson',5)");

        ReplayVolumeCheckResult result = service.check();

        assertThat(result.batch().status()).isEqualTo(ReplayVolumeCheckBatchStatus.WAITING_CONFIRM);
        assertThat(result.batch().catalogCount()).isEqualTo(3);
        assertThat(result.details()).extracting(ReplayVolumeCheckDetail::tranCode).containsExactlyInAnyOrder("T001", "T002", "T003");
        assertThat(result.details()).filteredOn(d -> d.tranCode().equals("T001")).singleElement().satisfies(d -> {
            assertThat(d.completeVolumeCount()).isEqualTo(3);
            assertThat(d.status()).isEqualTo(ReplayVolumeCheckDetailStatus.HAS_VOLUME);
        });
        assertThat(result.details()).filteredOn(d -> d.tranCode().equals("T002")).singleElement().satisfies(d -> assertThat(d.completeVolumeCount()).isEqualTo(3));
        assertThat(result.details()).filteredOn(d -> d.tranCode().equals("T003")).singleElement().satisfies(d -> assertThat(d.status()).isEqualTo(ReplayVolumeCheckDetailStatus.NO_VOLUME));
        assertThat(result.cleanupDetails()).filteredOn(d -> d.serviceCode().equals("unknown")).singleElement().satisfies(d -> {
            assertThat(d.catalogHit()).isFalse();
            assertThat(d.pendingCleanupRowCount()).isEqualTo(1);
        });
        assertThat(jdbc.getJdbcTemplate().queryForObject("select count(*) from msg_flow_log_request", Long.class)).isEqualTo(5L);
        assertThat(jdbc.getJdbcTemplate().queryForObject("select count(*) from msg_flow_log_response", Long.class)).isEqualTo(5L);
        assertThat(jdbc.getJdbcTemplate().queryForObject("select count(*) from information_schema.tables where table_name='ana_migration_command'", Long.class)).isZero();
    }

    @Test
    void normalizesServiceCodesWhenResolvingMappings() {
        jdbc.getJdbcTemplate().update("insert into ana_replay_transaction_catalog(tran_code) values ('DIRTY')");
        jdbc.getJdbcTemplate().update("insert into tp_online_service_in(tran_code,esf_service_code) values ('DIRTY',' D.i.R.t.Y. ')");
        jdbc.getJdbcTemplate().update("insert into msg_flow_log_request values ('ip','dirty-1',' DiR.Ty &SoP ',1)");
        jdbc.getJdbcTemplate().update("insert into msg_flow_log_response values ('ip','dirty-1',' dirty&sop ',1)");

        ReplayVolumeCheckResult result = service.check();

        assertThat(result.details()).singleElement().satisfies(d -> {
            assertThat(d.tranCode()).isEqualTo("DIRTY");
            assertThat(d.mappedServiceCount()).isEqualTo(1);
            assertThat(d.completeVolumeCount()).isEqualTo(1);
            assertThat(d.status()).isEqualTo(ReplayVolumeCheckDetailStatus.HAS_VOLUME);
        });
    }

    @Test
    void rollsBackBatchWhenDetailPersistenceFails() {
        jdbc.getJdbcTemplate().update("insert into ana_replay_transaction_catalog(tran_code) values ('ROLLBACK')");
        jdbc.getJdbcTemplate().update("insert into msg_flow_log_request values ('ip','rollback-1','UNKNOWN&bzjson',1)");
        jdbc.getJdbcTemplate().update("insert into msg_flow_log_response values ('ip','rollback-1','UNKNOWN&bzjson',1)");
        jdbc.getJdbcTemplate().execute("drop table ana_replay_volume_cleanup_detail");

        org.assertj.core.api.Assertions.assertThatThrownBy(() -> service.check())
                .isInstanceOf(RuntimeException.class);
        assertThat(jdbc.getJdbcTemplate().queryForObject("select count(*) from ana_replay_volume_check_batch", Long.class)).isZero();
        assertThat(jdbc.getJdbcTemplate().queryForObject("select count(*) from ana_replay_volume_check_detail", Long.class)).isZero();
    }
}
