spring.application.name=rose
spring.datasource.url=jdbc:postgresql://localhost:15432/postgres
spring.datasource.username=tss
spring.datasource.password=ENC(8MOwMno5IkR1Y/qdSa1OlSolUv29LvWz4qFRbKRda8avQmZ/JnXklqpEauzUaet3)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.thymeleaf.cache=false
server.port=8080
rose.datasource.bxds.url=${BXDS_DATASOURCE_URL:jdbc:postgresql://localhost:15432/postgres}
rose.datasource.bxds.username=${BXDS_DATASOURCE_USERNAME:adp}
rose.datasource.bxds.password=${BXDS_DATASOURCE_PASSWORD:ENC(b7YgDc16z3NdSLQOxQgxU398q07fvqMyTiYAQI2+XSh3qTw1cZPMRJ8ClTr52xUk)}
rose.datasource.bxds.driver-class-name=${BXDS_DATASOURCE_DRIVER:org.postgresql.Driver}
rose.mapping-doc.url-template=${MAPPING_DOC_URL_TEMPLATE:http://localhost:8888/serviceGovOut/OutInterface/downloadMappingFile.action?param=multi,{codes},MAPPING9}
rose.mapping-doc.batch-size=${MAPPING_DOC_BATCH_SIZE:10}
