spring.application.name=rose
spring.datasource.url=jdbc:postgresql://localhost:15432/postgres
spring.datasource.username=tss
spring.datasource.password=Tss@123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.default_schema=tss
spring.thymeleaf.cache=false
server.port=8080
rose.datasource.bxds.url=${BXDS_DATASOURCE_URL:jdbc:postgresql://localhost:15432/postgres}
rose.datasource.bxds.username=${BXDS_DATASOURCE_USERNAME:tss}
rose.datasource.bxds.password=${BXDS_DATASOURCE_PASSWORD:Tss@123456}
rose.datasource.bxds.driver-class-name=${BXDS_DATASOURCE_DRIVER:org.postgresql.Driver}
