package com.spdb.report;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class ReplayCoverageServiceTest {
    private JdbcTemplate jdbc;
    private ReplayCoverageService service;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource ds = new DriverManagerDataSource("jdbc:h2:mem:replay_coverage_" + UUID.randomUUID() + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = new JdbcTemplate(ds);
        service = new ReplayCoverageService(new NamedParameterJdbcTemplate(ds));
        jdbc.execute("create table ana_replay_transaction_catalog(tran_code varchar(200) primary key, tran_name varchar(200), business_domain varchar(200), new_service_scene_code varchar(200), replay_required varchar(200), latest_transaction_date varchar(200))");
        jdbc.execute("create table ana_tran_catalog(tran_code varchar(32), service_code varchar(200), owner varchar(100), internal_owner varchar(100))");
        jdbc.execute("create table ana_report_export_interface_summary(batch_id varchar(64), service_code varchar(200), sent_transaction_count bigint default 0)");
        jdbc.execute("create table ana_report_export_replay_coverage(coverage_id bigint generated by default as identity primary key, batch_id varchar(64), report_date varchar(8), tran_code varchar(200), tran_name varchar(200), business_domain varchar(200), new_service_scene_code varchar(200), resolved_service_codes varchar(1000), service_mapping_status varchar(32), replay_required varchar(200), latest_transaction_date varchar(200), sent_transaction_count bigint, coverage_status varchar(32), unsent_reason varchar(200), owner varchar(100), internal_owner varchar(100))");
    }

    @Test
    void resolvesMissingCatalogServiceCodeByTransactionCodeAndAggregatesSentVolume() {
        jdbc.update("insert into ana_replay_transaction_catalog values ('T001','交易一','支付',null,'是','20260830'),('T002','交易二','支付','S003','是','20260717')");
        jdbc.update("insert into ana_tran_catalog values ('T001','S001','开发甲','行内甲'),('T001','S002','开发甲','行内甲')");
        jdbc.update("insert into ana_report_export_interface_summary values ('B1','S001',3),('B1','S002',2),('B1','S003',0)");

        service.materialize("B1", "20260831");

        assertThat(jdbc.queryForMap("select * from ana_report_export_replay_coverage where tran_code='T001'")).containsEntry("resolved_service_codes", "S001,S002").containsEntry("sent_transaction_count", 5L).containsEntry("coverage_status", "已发送");
        assertThat(jdbc.queryForObject("select unsent_reason from ana_report_export_replay_coverage where tran_code='T002'", String.class)).isEqualTo("近期无交易");
    }

    @Test
    void treatsServiceWithoutBatchSummaryAsZeroInsteadOfFailingBatch() {
        jdbc.update("insert into ana_replay_transaction_catalog values ('T003','交易三','支付','S004','是','20260830')");

        service.materialize("B1", "20260831");

        assertThat(jdbc.queryForObject("select sent_transaction_count from ana_report_export_replay_coverage where tran_code='T003'", Long.class)).isZero();
    }

    @Test
    void treatsMissingLatestDateAsRecentNoTransactionWhenReplayRequired() {
        assertThat(ReplayCoverageService.unsentReason("是", null)).isEqualTo("近期无交易");
        assertThat(ReplayCoverageService.unsentReason("是", "")).isEqualTo("近期无交易");
        assertThat(ReplayCoverageService.unsentReason("是", "   ")).isEqualTo("近期无交易");
    }

    @Test
    void keepsMissingMappingStatusButAssignsNoReplayReasonFromFullCatalog() {
        jdbc.update("insert into ana_replay_transaction_catalog values ('T004','交易四','支付',null,'否','20260830')");

        service.materialize("B1", "20260831");

        assertThat(jdbc.queryForMap("select coverage_status, unsent_reason from ana_report_export_replay_coverage where tran_code='T004'"))
                .containsEntry("coverage_status", "缺少S码映射")
                .containsEntry("unsent_reason", "不回放");
    }
}
