package com.spdb.report;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.FillPatternType;
import org.apache.poi.ss.usermodel.Font;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.ss.usermodel.WorkbookFactory;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xssf.usermodel.XSSFCellStyle;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.time.LocalDate;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.within;

class ReportExportExcelServiceTest {
    private JdbcTemplate jdbc;
    private ReportExportExcelService service;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:report_excel_" + UUID.randomUUID() + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "sa", "");
        jdbc = new JdbcTemplate(dataSource);
        service = new ReportExportExcelService(new NamedParameterJdbcTemplate(dataSource));
        jdbc.execute("create table ana_report_export_command(command_id bigint generated by default as identity primary key, batch_id varchar(64) not null, report_date varchar(8) not null, status varchar(32) not null, created_time timestamp not null)");
        jdbc.execute("create table ana_report_export_summary(batch_id varchar(64), report_date varchar(8), module_name varchar(100), covered_528_interface_count bigint, sent_transaction_count bigint, comp_result_1_count bigint, comp_result_2_count bigint, comp_result_3_count bigint, comp_result_4_count bigint, comp_result_8_count bigint, success_rate decimal(12,8), diff_528_field_count bigint, field_pass_transaction_count bigint not null default 0, comparison_pass_rate decimal(12,8) not null default 0, transaction_issue_count bigint not null default 0, field_issue_count bigint not null default 0, issue_total_count bigint not null default 0, duplicate_issue_count bigint not null default 0)");
        jdbc.execute("create table ana_tran_diff_tracking_export(source_batch_id varchar(64), module_name varchar(100), row_no bigint, issue_id bigint, issue_key varchar(600), tran_code varchar(32), tran_name varchar(200), transaction_owner varchar(100), tran_seq_no varchar(64), problem_level varchar(100), registration_date varchar(8), field_name varchar(500), problem_description varchar(2000), problem_type varchar(100), preliminary_analysis varchar(2000), final_solution varchar(2000), resolution_date varchar(8), coordination_required varchar(100), resolver varchar(100), defect_fix_date varchar(8), historical_occurrence_count bigint not null default 0, first_seen_date date, previous_seen_date date)");
        jdbc.execute("create table ana_field_diff_tracking_export(source_batch_id varchar(64), module_name varchar(100), row_no bigint, issue_id bigint, issue_key varchar(600), tran_code varchar(32), tran_name varchar(200), transaction_owner varchar(100), tran_seq_no varchar(64), problem_level varchar(100), registration_date varchar(8), field_name varchar(500), problem_description varchar(2000), problem_type varchar(100), preliminary_analysis varchar(2000), final_solution varchar(2000), resolution_date varchar(8), coordination_required varchar(100), resolver varchar(100), defect_fix_date varchar(8), orig_field_value varchar(2000), dest_field_value varchar(2000), historical_occurrence_count bigint not null default 0, first_seen_date date, previous_seen_date date)");
    }

    @Test
    void streamsSummaryAndUnifiedDomainDetailsWithIssueHistoryWithoutFieldValues() throws Exception {
        jdbc.update("""
                insert into ana_report_export_summary(batch_id,report_date,module_name,covered_528_interface_count,
                    sent_transaction_count,comp_result_1_count,comp_result_2_count,comp_result_3_count,
                    comp_result_4_count,comp_result_8_count,success_rate,diff_528_field_count,
                    field_pass_transaction_count,comparison_pass_rate,transaction_issue_count,field_issue_count,
                    issue_total_count,duplicate_issue_count)
                values ('RPT1','20260727','支付',1,10,1,2,3,4,5,0.7,6,4,0.7,1,5,6,2)
                """);
        jdbc.update("""
                insert into ana_tran_diff_tracking_export(source_batch_id,module_name,row_no,tran_code,tran_name,
                    problem_level,registration_date,field_name,problem_description,historical_occurrence_count,
                    first_seen_date,previous_seen_date,defect_fix_date)
                values ('RPT1','支付',1,'T1','交易一','交易级','20260727','528失败/CCBS成功','交易描述',3,?,?, '20260725')
                """, LocalDate.parse("2026-07-01"), LocalDate.parse("2026-07-20"));
        jdbc.update("""
                insert into ana_field_diff_tracking_export(source_batch_id,module_name,row_no,tran_code,tran_name,
                    problem_level,registration_date,field_name,problem_description,orig_field_value,dest_field_value,
                    historical_occurrence_count,first_seen_date,previous_seen_date)
                values ('RPT1','支付',1,'T1','交易一','字段级','20260727','A | B','528：有值；CCBS：无值','secret','',2,?,?)
                """, LocalDate.parse("2026-07-02"), LocalDate.parse("2026-07-18"));
        ByteArrayOutputStream output = new ByteArrayOutputStream();

        service.stream("RPT1", output);

        try (Workbook workbook = WorkbookFactory.create(new ByteArrayInputStream(output.toByteArray()))) {
            assertThat(workbook.getSheetAt(0).getSheetName()).isEqualTo("汇总信息");
            assertCellFill(workbook.getSheetAt(0).getRow(0), 0, "B7D7C0");
            assertCellFill(workbook.getSheetAt(0).getRow(1), 4, "C6E0B4");
            assertCellFill(workbook.getSheetAt(0).getRow(2), 4, "E2F0D9");
            assertHeaderStyle(workbook, workbook.getSheet("支付").getRow(0), 0, "0E566F");
            assertCellFill(workbook.getSheetAt(0).getRow(8), 0, "FFFFFF");
            assertCellFill(workbook.getSheet("支付").getRow(1), 0, "BDE7F4");
            assertCellFill(workbook.getSheet("支付").getRow(2), 0, "FFFFFF");
            assertThat(workbook.getSheetAt(0).getRow(2).getCell(6).getStringCellValue()).isEqualTo("二者均失败响应码一致");
            assertThat(workbook.getSheetAt(0).getRow(2).getCell(7).getStringCellValue()).isEqualTo("二者均失败响应码不一致");
            assertThat(workbook.getSheetAt(0).getRow(2).getCell(8).getStringCellValue()).isEqualTo("二者均成功");
            assertThat(workbook.getSheetAt(0).getRow(8).getCell(7).getStringCellValue()).isEqualTo("5");
            assertThat(workbook.getSheetAt(0).getRow(8).getCell(8).getStringCellValue()).isEqualTo("4");
            assertPercentCell(workbook.getSheetAt(0).getRow(8), 9, 0.7d);
            assertThat(workbook.getSheet("支付").getPaneInformation().isFreezePane()).isTrue();
            assertThat(workbook.getSheet("支付").getRow(0).getCell(19).getStringCellValue()).isEqualTo("历史出现次数");
            assertThat(workbook.getSheet("支付").getRow(1).getCell(5).getStringCellValue()).isEqualTo("交易级");
            assertThat(workbook.getSheet("支付").getRow(1).getCell(19).getStringCellValue()).isEqualTo("3");
            assertThat(workbook.getSheet("支付").getRow(1).getCell(20).getStringCellValue()).isEqualTo("2026-07-01");
            assertThat(workbook.getSheet("支付").getRow(1).getCell(21).getStringCellValue()).isEqualTo("2026-07-20");
            assertThat(workbook.getSheet("支付").getRow(2).getCell(8).getStringCellValue()).isEqualTo("528：有值；CCBS：无值");
            assertThat(workbook.getSheet("支付").getRow(0).getCell(17).getStringCellValue()).isEqualTo("缺陷修复日期");
            assertThat(workbook.getSheet("支付").getRow(1).getCell(17).getStringCellValue()).isEqualTo("20260725");
            assertThat(workbook.getSheet("支付").getRow(0).getCell(18).getStringCellValue()).isEqualTo("备注");
            assertThat(workbook.getSheet("支付").getRow(1).getCell(18).getStringCellValue()).isBlank();
            assertThat(workbook.getSheet("支付").getRow(2).getCell(19).getStringCellValue()).isEqualTo("2");
        }
        assertThat(output.toString()).doesNotContain("secret");
    }

    @Test
    void dailyExportAddsDelayDistributionSheetWithoutRemovingExistingSheets() throws Exception {
        jdbc.update("insert into ana_report_export_command(batch_id,report_date,status,created_time) values ('RPT0','20260726','SUCCEEDED','2026-07-26 09:00:00')");
        jdbc.update("insert into ana_report_export_command(batch_id,report_date,status,created_time) values ('RPT1','20260728','SUCCEEDED','2026-07-28 09:00:00')");
        insertSummary("RPT1", "20260727", "支付", 6, 2);
        insertSummary("RPT0", "20260726", "支付", 4, 0);
        insertIssue("ana_tran_diff_tracking_export", "RPT0", "支付", "T1", "张三", "ISSUE-A", 0, LocalDate.parse("2026-07-26"));
        insertIssue("ana_tran_diff_tracking_export", "RPT0", "支付", "T2", "张三", "ISSUE-B", 0, LocalDate.parse("2026-07-25"));
        insertIssue("ana_tran_diff_tracking_export", "RPT0", "支付", "T3", "李四", "ISSUE-C", 0, LocalDate.parse("2026-07-24"));
        insertIssue("ana_field_diff_tracking_export", "RPT0", "贷款", "T4", "李四", "ISSUE-D", 0, LocalDate.parse("2026-07-23"));
        insertIssue("ana_tran_diff_tracking_export", "RPT1", "支付", "T1", "张三", "ISSUE-A", 1, LocalDate.parse("2026-07-27"));
        insertIssue("ana_field_diff_tracking_export", "RPT1", "支付", "T1", "张三", "ISSUE-E", 4, LocalDate.parse("2026-07-23"));
        insertIssue("ana_tran_diff_tracking_export", "RPT1", "贷款", "T2", "李四", "ISSUE-F", 2, LocalDate.parse("2026-07-25"));
        insertIssue("ana_tran_diff_tracking_export", "RPT1", "贷款", "T5", null, "王五", "ISSUE-G", 0, LocalDate.parse("2026-07-28"));
        ByteArrayOutputStream output = new ByteArrayOutputStream();

        service.stream("RPT1", output);

        try (Workbook workbook = WorkbookFactory.create(new ByteArrayInputStream(output.toByteArray()))) {
            assertThat(workbook.getSheet("汇总信息")).isNotNull();
            Sheet sheet = workbook.getSheet("问题处理延迟分布");
            assertThat(sheet).isNotNull();
            assertThat(sheet.getRow(4).getCell(0).getStringCellValue()).isEqualTo("解决人员");
            assertThat(sheet.getRow(4).getCell(4).getStringCellValue()).isEqualTo("延期1天");
            Row zhangSanDelay = findRow(sheet, 5, "张三");
            assertThat(zhangSanDelay.getCell(1).getStringCellValue()).isEqualTo("1");
            assertThat(zhangSanDelay.getCell(2).getStringCellValue()).isEqualTo("2");
            assertThat(zhangSanDelay.getCell(3).getStringCellValue()).isEqualTo("1");
            assertThat(zhangSanDelay.getCell(4).getStringCellValue()).isEqualTo("1");
            assertThat(zhangSanDelay.getCell(8).getStringCellValue()).isEqualTo("0");
            Row repeatHeader = findRow(sheet, 0, "解决人员", "重复1次");
            Row zhangSanRepeat = findRow(sheet, repeatHeader.getRowNum() + 1, "张三");
            assertThat(zhangSanRepeat.getCell(5).getStringCellValue()).isEqualTo("1");
            assertThat(zhangSanRepeat.getCell(8).getStringCellValue()).isEqualTo("1");
            Row ownerFallback = findRow(sheet, 5, "王五");
            assertThat(ownerFallback.getCell(1).getStringCellValue()).isEqualTo("1");
            assertThat(ownerFallback.getCell(2).getStringCellValue()).isEqualTo("1");
        }
    }

    @Test
    void weeklyExportUsesSucceededBatchFromOneWeekEarlierAndGroupsDelayByModule() throws Exception {
        jdbc.update("insert into ana_report_export_command(batch_id,report_date,status,created_time) values ('RPT-WEEK','20260721','SUCCEEDED','2026-07-21 09:00:00')");
        jdbc.update("insert into ana_report_export_command(batch_id,report_date,status,created_time) values ('RPT-MID','20260727','SUCCEEDED','2026-07-27 09:00:00')");
        jdbc.update("insert into ana_report_export_command(batch_id,report_date,status,created_time) values ('RPT-CURRENT','20260728','SUCCEEDED','2026-07-28 09:00:00')");
        insertSummary("RPT-WEEK", "20260721", "支付", 12, 0);
        insertSummary("RPT-MID", "20260727", "支付", 99, 0);
        insertSummary("RPT-CURRENT", "20260728", "支付", 8, 3);
        insertIssue("ana_tran_diff_tracking_export", "RPT-WEEK", "支付", "T1", "张三", "ISSUE-A", 0, LocalDate.parse("2026-07-21"));
        insertIssue("ana_field_diff_tracking_export", "RPT-WEEK", "支付", "T2", "李四", "ISSUE-B", 0, LocalDate.parse("2026-07-21"));
        insertIssue("ana_tran_diff_tracking_export", "RPT-WEEK", "支付", "T3", "李四", "ISSUE-C", 0, LocalDate.parse("2026-07-20"));
        insertIssue("ana_tran_diff_tracking_export", "RPT-CURRENT", "支付", "T1", "张三", "ISSUE-A", 1, LocalDate.parse("2026-07-27"));
        insertIssue("ana_field_diff_tracking_export", "RPT-CURRENT", "支付", "T2", "李四", "ISSUE-D", 2, LocalDate.parse("2026-07-24"));
        ByteArrayOutputStream output = new ByteArrayOutputStream();

        service.streamWeekly("RPT-CURRENT", output);

        try (Workbook workbook = WorkbookFactory.create(new ByteArrayInputStream(output.toByteArray()))) {
            Sheet summary = workbook.getSheet("汇总信息");
            assertThat(summary.getRow(0).getCell(0).getStringCellValue()).contains("周期周报").contains("RPT-WEEK");
            assertThat(java.util.stream.IntStream.range(0, 20)
                    .mapToObj(summary::getRow)
                    .filter(java.util.Objects::nonNull)
                    .map(row -> row.getCell(0).getStringCellValue())
                    .anyMatch(value -> value.contains("RPT-CURRENT"))).isTrue();
            Row currentPay = findRow(summary, 8, "RPT-CURRENT");
            assertThat(currentPay.getCell(12).getStringCellValue()).isEqualTo("1");
            assertPercentCell(currentPay, 13, 11d / 12d);
            Sheet distribution = workbook.getSheet("问题处理延迟分布");
            assertThat(distribution.getRow(4).getCell(0).getStringCellValue()).isEqualTo("领域");
            Row payDelay = findRow(distribution, 5, "支付");
            assertThat(payDelay.getCell(1).getStringCellValue()).isEqualTo("2");
            assertThat(payDelay.getCell(2).getStringCellValue()).isEqualTo("2");
            assertThat(payDelay.getCell(3).getStringCellValue()).isEqualTo("2");
            assertThat(payDelay.getCell(4).getStringCellValue()).isEqualTo("0");
            assertThat(payDelay.getCell(7).getStringCellValue()).isEqualTo("0");
        }
    }

    @Test
    void weeklyExportFallsBackToNearestSucceededBatchAfterTargetDateWhenNoEarlierBatchExists() throws Exception {
        jdbc.update("insert into ana_report_export_command(batch_id,report_date,status,created_time) values ('RPT-AFTER-1','20260723','SUCCEEDED','2026-07-23 09:00:00')");
        jdbc.update("insert into ana_report_export_command(batch_id,report_date,status,created_time) values ('RPT-AFTER-2','20260725','SUCCEEDED','2026-07-25 09:00:00')");
        jdbc.update("insert into ana_report_export_command(batch_id,report_date,status,created_time) values ('RPT-CURRENT','20260729','SUCCEEDED','2026-07-29 09:00:00')");
        insertSummary("RPT-AFTER-1", "20260723", "支付", 12, 0);
        insertSummary("RPT-AFTER-2", "20260725", "支付", 99, 0);
        insertSummary("RPT-CURRENT", "20260729", "支付", 8, 3);
        ByteArrayOutputStream output = new ByteArrayOutputStream();

        service.streamWeekly("RPT-CURRENT", output);

        try (Workbook workbook = WorkbookFactory.create(new ByteArrayInputStream(output.toByteArray()))) {
            Sheet summary = workbook.getSheet("汇总信息");
            assertThat(summary.getRow(0).getCell(0).getStringCellValue())
                    .contains("周期周报")
                    .contains("RPT-AFTER-1")
                    .doesNotContain("RPT-AFTER-2");
        }
    }

    @Test
    void exportLogsDailyAndWeeklyProgress() throws Exception {
        jdbc.update("insert into ana_report_export_command(batch_id,report_date,status,created_time) values ('RPT-WEEK','20260721','SUCCEEDED','2026-07-21 09:00:00')");
        jdbc.update("insert into ana_report_export_command(batch_id,report_date,status,created_time) values ('RPT-CURRENT','20260728','SUCCEEDED','2026-07-28 09:00:00')");
        insertSummary("RPT-WEEK", "20260721", "鏀粯", 12, 0);
        insertSummary("RPT-CURRENT", "20260728", "鏀粯", 8, 1);

        ListAppender<ILoggingEvent> appender = attachAppender();
        try {
            service.stream("RPT-CURRENT", new ByteArrayOutputStream());
            service.streamWeekly("RPT-CURRENT", new ByteArrayOutputStream());
        } finally {
            detachAppender(appender);
        }

        assertThat(appender.list).anySatisfy(event -> {
            assertThat(event.getLevel()).isEqualTo(Level.INFO);
            assertThat(event.getFormattedMessage())
                    .contains("日报导出开始")
                    .contains("batchId=RPT-CURRENT");
        });
        assertThat(appender.list).anySatisfy(event -> {
            assertThat(event.getLevel()).isEqualTo(Level.INFO);
            assertThat(event.getFormattedMessage())
                    .contains("日报导出完成")
                    .contains("batchId=RPT-CURRENT")
                    .contains("elapsedMs=");
        });
        assertThat(appender.list).anySatisfy(event -> {
            assertThat(event.getLevel()).isEqualTo(Level.INFO);
            assertThat(event.getFormattedMessage())
                    .contains("周报基准批次命中")
                    .contains("batchId=RPT-CURRENT")
                    .contains("baselineBatchId=RPT-WEEK");
        });
        assertThat(appender.list).anySatisfy(event -> {
            assertThat(event.getLevel()).isEqualTo(Level.INFO);
            assertThat(event.getFormattedMessage())
                    .contains("周报导出完成")
                    .contains("batchId=RPT-CURRENT")
                    .contains("baselineBatchId=RPT-WEEK")
                    .contains("elapsedMs=");
        });
    }

    @Test
    void streamsPreviousAndCurrentBatchSummarySheetWithApprovedMetrics() throws Exception {
        jdbc.update("""
                insert into ana_report_export_command(batch_id,report_date,status,created_time)
                values ('RPT20260716-101530-2048','20260716','SUCCEEDED','2026-07-16 10:15:30')
                """);
        jdbc.update("""
                insert into ana_report_export_command(batch_id,report_date,status,created_time)
                values ('RPT20260720-090000-1111','20260720','FAILED','2026-07-20 09:00:00')
                """);
        jdbc.update("""
                insert into ana_report_export_command(batch_id,report_date,status,created_time)
                values ('RPT20260728-132831-6664','20260728','SUCCEEDED','2026-07-28 13:28:31')
                """);
        insertSummary("RPT20260716-101530-2048", "20260716", "支付", 15, 0);
        insertSummary("RPT20260716-101530-2048", "20260716", "贷款", 5, 0);
        insertSummary("RPT20260728-132831-6664", "20260728", "支付", 9, 3);
        ByteArrayOutputStream output = new ByteArrayOutputStream();

        service.stream("RPT20260728-132831-6664", output);

        try (Workbook workbook = WorkbookFactory.create(new ByteArrayInputStream(output.toByteArray()))) {
            assertThat(workbook.getSheetAt(0).getSheetName()).isEqualTo("汇总信息");
            assertThat(workbook.getSheetIndex("汇总信息")).isZero();
            assertThat(workbook.getSheet("问题处理延迟分布")).isNotNull();

            var sheet = workbook.getSheetAt(0);
            assertThat(sheet.getPaneInformation()).isNull();
            assertThat(sheet.getRow(0).getCell(0).getStringCellValue())
                    .isEqualTo("批次号：RPT20260716-101530-2048（上一批次）");
            assertMergedRegion(sheet, 0, 0, 0, 17);
            assertCellFill(sheet.getRow(0), 0, "B7D7C0");
            assertCellFontColor(workbook, sheet.getRow(0), 0, (short) 8);
            assertMainHeaders(sheet.getRow(1), false);
            assertCellFill(sheet.getRow(1), 0, "C6E0B4");
            assertCellFontColor(workbook, sheet.getRow(1), 0, (short) 8);
            assertCellFill(sheet.getRow(1), 4, "C6E0B4");
            assertCellFill(sheet.getRow(1), 11, "FFF2CC");
            assertCellFontColor(workbook, sheet.getRow(1), 11, (short) 8);
            assertCellFill(sheet.getRow(1), 12, "FFF8E1");
            assertCellFill(sheet.getRow(1), 17, "FFF8E1");
            assertThat(sheet.getRow(1).getHeightInPoints()).isGreaterThanOrEqualTo(28f);
            assertThat(sheet.getRow(2).getHeightInPoints()).isGreaterThanOrEqualTo(42f);
            assertSubHeaders(sheet.getRow(2), 4, 12);
            assertCellFill(sheet.getRow(2), 4, "E2F0D9");
            assertCellFill(sheet.getRow(2), 12, "FFF8E1");
            assertMergedRegion(sheet, 1, 2, 0, 0);
            assertMergedRegion(sheet, 1, 2, 1, 1);
            assertMergedRegion(sheet, 1, 2, 2, 2);
            assertMergedRegion(sheet, 1, 2, 3, 3);
            assertMergedRegion(sheet, 1, 1, 4, 8);
            assertMergedRegion(sheet, 1, 2, 9, 9);
            assertMergedRegion(sheet, 1, 2, 10, 10);
            assertMergedRegion(sheet, 1, 2, 11, 11);
            assertMergedRegion(sheet, 1, 1, 12, 16);
            assertMergedRegion(sheet, 1, 2, 17, 17);

            assertThat(sheet.getRow(3).getCell(0).getStringCellValue()).isEqualTo("RPT20260716-101530-2048");
            assertCellFill(sheet.getRow(3), 0, "FFFFFF");
            assertThat(sheet.getRow(3).getCell(1).getStringCellValue()).isEqualTo("支付");
            assertThat(sheet.getRow(3).getCell(2).getStringCellValue()).isEqualTo("1");
            assertThat(sheet.getRow(3).getCell(3).getStringCellValue()).isEqualTo("10");
            assertThat(sheet.getRow(3).getCell(4).getStringCellValue()).isEqualTo("1");
            assertThat(sheet.getRow(3).getCell(5).getStringCellValue()).isEqualTo("2");
            assertThat(sheet.getRow(3).getCell(6).getStringCellValue()).isEqualTo("3");
            assertThat(sheet.getRow(3).getCell(7).getStringCellValue()).isEqualTo("5");
            assertThat(sheet.getRow(3).getCell(8).getStringCellValue()).isEqualTo("4");
            assertPercentCell(sheet.getRow(3), 9, 0.7d);
            assertPercentCell(sheet.getRow(3), 10, 0.7d);
            assertThat(sheet.getRow(3).getCell(11).getStringCellValue()).isEqualTo("15");
            assertBlankCells(sheet.getRow(3), 12, 17);
            assertCellFill(sheet.getRow(3), 12, "FFF8E1");

            assertThat(sheet.getRow(4).getCell(1).getStringCellValue()).isEqualTo("贷款");
            assertCellFill(sheet.getRow(4), 0, "FFFFFF");
            assertThat(sheet.getRow(4).getCell(11).getStringCellValue()).isEqualTo("5");
            assertBlankCells(sheet.getRow(4), 12, 17);

            assertThat(sheet.getRow(5).getCell(1).getStringCellValue()).isEqualTo("合计");
            assertCellFill(sheet.getRow(5), 0, "EEF2F7");
            assertPercentCell(sheet.getRow(5), 9, 0.7d);
            assertPercentCell(sheet.getRow(5), 10, 0.7d);
            assertThat(sheet.getRow(5).getCell(11).getStringCellValue()).isEqualTo("20");
            assertBlankCells(sheet.getRow(5), 12, 17);
            assertThat(sheet.getRow(6)).isNull();

            assertThat(sheet.getRow(7).getCell(0).getStringCellValue())
                    .isEqualTo("批次号：RPT20260728-132831-6664（本批次）");
            assertMergedRegion(sheet, 7, 7, 0, 19);
            assertCellFill(sheet.getRow(7), 0, "F4CCCC");
            assertMainHeaders(sheet.getRow(8), true);
            assertCellFill(sheet.getRow(8), 0, "FCE4D6");
            assertCellFill(sheet.getRow(8), 4, "FCE4D6");
            assertCellFill(sheet.getRow(8), 11, "FFF2CC");
            assertCellFill(sheet.getRow(8), 12, "FFF2CC");
            assertCellFill(sheet.getRow(8), 13, "FFF2CC");
            assertCellFill(sheet.getRow(8), 14, "FFF8E1");
            assertCellFill(sheet.getRow(8), 19, "FFF8E1");
            assertThat(sheet.getRow(8).getHeightInPoints()).isGreaterThanOrEqualTo(28f);
            assertThat(sheet.getRow(9).getHeightInPoints()).isGreaterThanOrEqualTo(42f);
            assertSubHeaders(sheet.getRow(9), 4, 14);
            assertCellFill(sheet.getRow(9), 4, "FCE4D6");
            assertCellFill(sheet.getRow(9), 14, "FFF8E1");
            assertMergedRegion(sheet, 8, 9, 0, 0);
            assertMergedRegion(sheet, 8, 9, 1, 1);
            assertMergedRegion(sheet, 8, 9, 2, 2);
            assertMergedRegion(sheet, 8, 9, 3, 3);
            assertMergedRegion(sheet, 8, 8, 4, 8);
            assertMergedRegion(sheet, 8, 9, 9, 9);
            assertMergedRegion(sheet, 8, 9, 10, 10);
            assertMergedRegion(sheet, 8, 9, 11, 11);
            assertMergedRegion(sheet, 8, 9, 12, 12);
            assertMergedRegion(sheet, 8, 9, 13, 13);
            assertMergedRegion(sheet, 8, 8, 14, 18);
            assertMergedRegion(sheet, 8, 9, 19, 19);

            assertThat(sheet.getRow(10).getCell(0).getStringCellValue()).isEqualTo("RPT20260728-132831-6664");
            assertCellFill(sheet.getRow(10), 0, "FFFFFF");
            assertThat(sheet.getRow(10).getCell(1).getStringCellValue()).isEqualTo("支付");
            assertThat(sheet.getRow(10).getCell(11).getStringCellValue()).isEqualTo("9");
            assertThat(sheet.getRow(10).getCell(12).getStringCellValue()).isEqualTo("3");
            assertPercentCell(sheet.getRow(10), 13, 12d / 15d);
            assertBlankCells(sheet.getRow(10), 14, 19);
            assertCellFill(sheet.getRow(10), 14, "FFF8E1");

            assertThat(sheet.getRow(11).getCell(1).getStringCellValue()).isEqualTo("合计");
            assertCellFill(sheet.getRow(11), 0, "F8F3F0");
            assertThat(sheet.getRow(11).getCell(11).getStringCellValue()).isEqualTo("9");
            assertThat(sheet.getRow(11).getCell(12).getStringCellValue()).isEqualTo("3");
            assertPercentCell(sheet.getRow(11), 9, 0.7d);
            assertPercentCell(sheet.getRow(11), 10, 0.7d);
            assertPercentCell(sheet.getRow(11), 13, 17d / 20d);
            assertBlankCells(sheet.getRow(11), 14, 19);
        }
    }

    private void insertSummary(String batchId, String reportDate, String module, long issueTotal, long duplicate) {
        jdbc.update("""
                insert into ana_report_export_summary(batch_id,report_date,module_name,covered_528_interface_count,
                    sent_transaction_count,comp_result_1_count,comp_result_2_count,comp_result_3_count,
                    comp_result_4_count,comp_result_8_count,success_rate,diff_528_field_count,
                    field_pass_transaction_count,comparison_pass_rate,transaction_issue_count,field_issue_count,
                    issue_total_count,duplicate_issue_count)
                values (?,?,?,1,10,1,2,3,4,5,0.70000000,6,4,0.70000000,4,5,?,?)
                """, batchId, reportDate, module, issueTotal, duplicate);
    }

    private void insertIssue(String table, String batchId, String module, String tranCode, String resolver,
                             String issueKey, long historicalCount, LocalDate firstSeenDate) {
        insertIssue(table, batchId, module, tranCode, resolver, resolver, issueKey, historicalCount, firstSeenDate);
    }

    private void insertIssue(String table, String batchId, String module, String tranCode, String resolver,
                             String transactionOwner, String issueKey, long historicalCount, LocalDate firstSeenDate) {
        jdbc.update("insert into " + table + "(source_batch_id,module_name,row_no,issue_id,issue_key,tran_code,tran_name,"
                        + "problem_description,transaction_owner,resolver,historical_occurrence_count,first_seen_date) "
                        + "values (?,?,?,?,?,?,?,?,?,?,?,?)",
                batchId, module, 1L, Math.abs(issueKey.hashCode()), issueKey, tranCode, "交易", "问题",
                transactionOwner, resolver, historicalCount, firstSeenDate);
    }

    private static Row findRow(Sheet sheet, int fromRow, String firstCellValue) {
        for (int rowIndex = fromRow; rowIndex <= sheet.getLastRowNum(); rowIndex++) {
            Row row = sheet.getRow(rowIndex);
            if (row != null && row.getCell(0) != null
                    && firstCellValue.equals(row.getCell(0).getStringCellValue())) {
                return row;
            }
        }
        throw new AssertionError("未找到首列为 " + firstCellValue + " 的行");
    }

    private static Row findRow(Sheet sheet, int fromRow, String firstCellValue, String fifthCellValue) {
        for (int rowIndex = fromRow; rowIndex <= sheet.getLastRowNum(); rowIndex++) {
            Row row = sheet.getRow(rowIndex);
            if (row != null && row.getCell(0) != null && row.getCell(4) != null
                    && firstCellValue.equals(row.getCell(0).getStringCellValue())
                    && fifthCellValue.equals(row.getCell(4).getStringCellValue())) {
                return row;
            }
        }
        throw new AssertionError("未找到首列为 " + firstCellValue + " 且第 5 列为 " + fifthCellValue + " 的行");
    }

    private static void assertPercentCell(Row row, int column, double expected) {
        assertThat(row.getCell(column).getCellType()).isEqualTo(CellType.NUMERIC);
        assertThat(row.getCell(column).getNumericCellValue()).isCloseTo(expected, within(0.00000001d));
        assertThat(row.getCell(column).getCellStyle().getDataFormatString()).isEqualTo("0.00%");
    }

    private static void assertBlankCells(Row row, int firstColumn, int lastColumn) {
        for (int column = firstColumn; column <= lastColumn; column++) {
            assertThat(row.getCell(column).getStringCellValue()).isBlank();
        }
    }

    private static void assertMainHeaders(Row row, boolean current) {
        assertThat(row.getCell(0).getStringCellValue()).isEqualTo("批次");
        assertThat(row.getCell(1).getStringCellValue()).isEqualTo("领域");
        assertThat(row.getCell(2).getStringCellValue()).isEqualTo("覆盖528接口");
        assertThat(row.getCell(3).getStringCellValue()).isEqualTo("发送交易量");
        assertThat(row.getCell(4).getStringCellValue()).isEqualTo("交易状态分类统计");
        assertThat(row.getCell(9).getStringCellValue()).isEqualTo("成功率");
        assertThat(row.getCell(10).getStringCellValue()).isEqualTo("比对通过率");
        assertThat(row.getCell(11).getStringCellValue()).isEqualTo("问题总数");
        if (current) {
            assertThat(row.getCell(12).getStringCellValue()).isEqualTo("重复问题");
            assertThat(row.getCell(13).getStringCellValue()).isEqualTo("上轮问题解决率");
            assertThat(row.getCell(14).getStringCellValue()).isEqualTo("已解决问题分类统计（待验证）");
            assertThat(row.getCell(19).getStringCellValue()).isEqualTo("问题解决进度");
        } else {
            assertThat(row.getCell(12).getStringCellValue()).isEqualTo("已解决问题分类统计（待验证）");
            assertThat(row.getCell(17).getStringCellValue()).isEqualTo("问题解决进度");
        }
    }

    private static void assertSubHeaders(Row row, int statusStartColumn, int solvedStartColumn) {
        assertThat(row.getCell(statusStartColumn).getStringCellValue()).isEqualTo("528成功/CCBS失败");
        assertThat(row.getCell(statusStartColumn + 1).getStringCellValue()).isEqualTo("528失败/CCBS成功");
        assertThat(row.getCell(statusStartColumn + 2).getStringCellValue()).isEqualTo("二者均失败响应码一致");
        assertThat(row.getCell(statusStartColumn + 3).getStringCellValue()).isEqualTo("二者均失败响应码不一致");
        assertThat(row.getCell(statusStartColumn + 4).getStringCellValue()).isEqualTo("二者均成功");
        assertThat(row.getCell(solvedStartColumn).getStringCellValue()).isEqualTo("迁移问题");
        assertThat(row.getCell(solvedStartColumn + 1).getStringCellValue()).isEqualTo("防腐问题");
        assertThat(row.getCell(solvedStartColumn + 2).getStringCellValue()).isEqualTo("功能问题");
        assertThat(row.getCell(solvedStartColumn + 3).getStringCellValue()).isEqualTo("新核心下线");
        assertThat(row.getCell(solvedStartColumn + 4).getStringCellValue()).isEqualTo("其他问题");
    }

    private static void assertMergedRegion(org.apache.poi.ss.usermodel.Sheet sheet, int firstRow, int lastRow,
                                           int firstColumn, int lastColumn) {
        assertThat(sheet.getMergedRegions())
                .contains(new CellRangeAddress(firstRow, lastRow, firstColumn, lastColumn));
    }

    private static void assertHeaderStyle(Workbook workbook, Row row, int column, String expectedRgb) {
        assertThat(row.getHeightInPoints()).isGreaterThanOrEqualTo(22f);
        var style = row.getCell(column).getCellStyle();
        assertThat(style.getFillPattern()).isEqualTo(FillPatternType.SOLID_FOREGROUND);
        assertThat(fillRgb(style)).isEqualTo(expectedRgb);
        Font font = workbook.getFontAt(style.getFontIndexAsInt());
        assertThat(font.getBold()).isTrue();
        assertThat(font.getColor()).isEqualTo((short) 9);
    }

    private static void assertCellFill(Row row, int column, String expectedRgb) {
        var style = row.getCell(column).getCellStyle();
        assertThat(style.getFillPattern()).isEqualTo(FillPatternType.SOLID_FOREGROUND);
        assertThat(fillRgb(style)).isEqualTo(expectedRgb);
    }

    private static void assertCellFontColor(Workbook workbook, Row row, int column, short expectedIndexedColor) {
        var style = row.getCell(column).getCellStyle();
        Font font = workbook.getFontAt(style.getFontIndexAsInt());
        assertThat(font.getColor()).isEqualTo(expectedIndexedColor);
    }

    private static String fillRgb(org.apache.poi.ss.usermodel.CellStyle style) {
        byte[] rgb = ((XSSFCellStyle) style).getFillForegroundXSSFColor().getRGB();
        return String.format("%02X%02X%02X", rgb[0] & 0xff, rgb[1] & 0xff, rgb[2] & 0xff);
    }

    private ListAppender<ILoggingEvent> attachAppender() {
        Logger logger = (Logger) LoggerFactory.getLogger(ReportExportExcelService.class);
        ListAppender<ILoggingEvent> appender = new ListAppender<>();
        appender.start();
        logger.addAppender(appender);
        return appender;
    }

    private void detachAppender(ListAppender<ILoggingEvent> appender) {
        Logger logger = (Logger) LoggerFactory.getLogger(ReportExportExcelService.class);
        logger.detachAppender(appender);
    }
}
