package com.spdb.report;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

class ReportExportCommandServiceTest {
    private JdbcTemplate jdbc;
    private ReportExportCommandService service;
    private String launchedBatchId;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:report_export_" + UUID.randomUUID() + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "sa", "");
        jdbc = new JdbcTemplate(dataSource);
        service = new ReportExportCommandService(new NamedParameterJdbcTemplate(dataSource), launcherProvider(),
                Clock.fixed(Instant.parse("2026-07-26T01:02:03Z"), ZoneOffset.UTC));
        createSchema();
    }

    @Test
    void createsPendingCommandForReportDateAndLaunchesIt() {
        String batchId = service.createAndStart("20260725");

        assertThat(batchId).matches("RPT20260726-010203-\\d{4}");
        assertThat(launchedBatchId).isEqualTo(batchId);
        assertThat(service.findByBatchId(batchId)).satisfies(row -> {
            assertThat(row.reportDate()).isEqualTo("20260725");
            assertThat(row.status()).isEqualTo("PENDING");
        });
    }

    @Test
    void transitionsOnlyThroughAllowedLifecycleStatesAndTruncatesFailure() {
        String batchId = service.createAndStart("20260725");

        assertThat(service.markRunning(batchId)).isTrue();
        assertThat(service.markRunning(batchId)).isFalse();
        service.markSucceeded(batchId);
        service.markFailed(batchId, "ignored");
        assertThat(service.findByBatchId(batchId).status()).isEqualTo("SUCCEEDED");

        String failedBatch = service.createAndStart("20260724");
        service.markFailed(failedBatch, "x".repeat(5000));
        assertThat(service.findByBatchId(failedBatch)).satisfies(row -> {
            assertThat(row.status()).isEqualTo("FAILED");
            assertThat(row.errorMessage()).hasSize(4000);
        });
    }

    @Test
    void returnsOnlyExportSummaryRowsForTheRequestedBatch() {
        String batchId = service.createAndStart("20260725");
        jdbc.update("insert into ana_report_export_summary(batch_id, report_date, module_name, sent_transaction_count) values (?, ?, ?, ?)",
                batchId, "20260725", "模块A", 11L);
        jdbc.update("insert into ana_report_export_summary(batch_id, report_date, module_name) values (?, ?, ?)",
                "RPT-OTHER", "20260724", "模块B");

        List<ReportExportSummaryRow> summaries = service.findSummaries(batchId);

        assertThat(summaries).singleElement().satisfies(row -> {
            assertThat(row.batchId()).isEqualTo(batchId);
            assertThat(row.moduleName()).isEqualTo("模块A");
            assertThat(row.sentTransactionCount()).isEqualTo(11L);
        });
    }

    private ObjectProvider<ReportExportTaskLauncher> launcherProvider() {
        ReportExportTaskLauncher launcher = batchId -> launchedBatchId = batchId;
        return new ObjectProvider<>() {
            @Override public ReportExportTaskLauncher getObject(Object... args) { return launcher; }
            @Override public ReportExportTaskLauncher getObject() { return launcher; }
            @Override public ReportExportTaskLauncher getIfAvailable() { return launcher; }
            @Override public ReportExportTaskLauncher getIfUnique() { return launcher; }
        };
    }

    private void createSchema() {
        jdbc.execute("create table ana_report_export_command(command_id bigint generated by default as identity primary key, batch_id varchar(64) not null unique, report_date varchar(8) not null, status varchar(32) not null, started_time timestamp, ended_time timestamp, error_message varchar(4000), created_time timestamp not null default current_timestamp, updated_at timestamp not null default current_timestamp)");
        jdbc.execute("create table ana_report_export_summary(summary_id bigint generated by default as identity primary key, batch_id varchar(64) not null, report_date varchar(8) not null, module_name varchar(100) not null, covered_528_interface_count bigint not null default 0, sent_transaction_count bigint not null default 0, comp_result_1_count bigint not null default 0, comp_result_2_count bigint not null default 0, comp_result_3_count bigint not null default 0, comp_result_4_count bigint not null default 0, comp_result_8_count bigint not null default 0, diff_528_field_count bigint not null default 0, success_rate decimal(12,8) not null default 0, created_time timestamp not null default current_timestamp, updated_at timestamp not null default current_timestamp)");
    }
}
