package com.spdb.config;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.io.OutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class ConfigImportServiceTest {

    private NamedParameterJdbcTemplate jdbc;
    private ConfigImportService service;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource("jdbc:h2:mem:config_import;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = new NamedParameterJdbcTemplate(dataSource);
        jdbc.getJdbcTemplate().execute("drop table if exists ana_field_mapping");
        jdbc.getJdbcTemplate().execute("drop table if exists ana_tran_catalog");
        jdbc.getJdbcTemplate().execute("""
                create table ana_tran_catalog (
                    catalog_id bigint generated by default as identity primary key,
                    tran_code varchar(32) not null,
                    service_code varchar(200) not null,
                    tran_name varchar(200),
                    module_name varchar(50),
                    owner varchar(100),
                    importance_level varchar(20),
                    is_key_tran varchar(5),
                    remark varchar(1000),
                    created_at timestamp default current_timestamp,
                    updated_at timestamp default current_timestamp,
                    unique (tran_code, service_code)
                )
                """);
        jdbc.getJdbcTemplate().execute("""
                create table ana_field_mapping (
                    mapping_id bigint generated by default as identity primary key,
                    tran_code varchar(32) not null,
                    service_code varchar(200) not null,
                    std_field_name varchar(200) not null,
                    field_cn_name varchar(200),
                    sop_field_name varchar(200),
                    soap_field_name varchar(200),
                    bizjson_field_name varchar(200),
                    remark varchar(1000),
                    created_at timestamp default current_timestamp,
                    updated_at timestamp default current_timestamp,
                    unique (tran_code, service_code, std_field_name)
                )
                """);
        service = new ConfigImportService(new ConfigWorkbookParser(), jdbc);
    }

    @Test
    void importsWorkbookIntoTransactionCatalogAndFieldMappingTables() throws Exception {
        Path workbook = writeWorkbook();
        ConfigImportResult result = service.importWorkbook(workbook, "A825+comm+张三.xlsx",
                "S030030014FcyCollCrspBnkLkgQry", null, null);

        assertThat(result.tranInserted()).isEqualTo(1);
        assertThat(result.fieldInserted()).isEqualTo(4);

        String tranName = jdbc.queryForObject("""
                select tran_name from ana_tran_catalog
                where tran_code = :tranCode and service_code = :serviceCode
                """, params(), String.class);
        assertThat(tranName).isEqualTo("外币托收代理行联动查询");

        List<String> sopFields = jdbc.query("""
                select sop_field_name from ana_field_mapping
                where tran_code = :tranCode and service_code = :serviceCode
                order by mapping_id
                """, params(), (rs, rowNum) -> rs.getString("sop_field_name"));
        assertThat(sopFields).containsExactly("HUOBDH", "FAB251", "TUOSFS", "DLZJMC");

        List<String> bizjsonFields = jdbc.query("""
                select bizjson_field_name from ana_field_mapping
                where tran_code = :tranCode and service_code = :serviceCode
                order by mapping_id
                """, params(), (rs, rowNum) -> rs.getString("bizjson_field_name"));
        assertThat(bizjsonFields).containsExactly("CurrencyId", "FcyCollCrspBnkLkgInfo", "RcrMtd", "AgentCtfType");
    }

    @Test
    void updatesExistingRowsOnSecondImport() throws Exception {
        Path workbook = writeWorkbook();
        service.importWorkbook(workbook, "A825+comm+张三.xlsx",
                "S030030014FcyCollCrspBnkLkgQry", null, null);

        ConfigImportResult result = service.importWorkbook(workbook, "A825+loan+李四.xlsx",
                "S030030014FcyCollCrspBnkLkgQry", null, "李四");

        assertThat(result.tranUpdated()).isEqualTo(1);
        assertThat(result.fieldUpdated()).isEqualTo(4);
        String owner = jdbc.queryForObject("""
                select owner from ana_tran_catalog
                where tran_code = :tranCode and service_code = :serviceCode
                """, params(), String.class);
        assertThat(owner).isEqualTo("李四");
    }

    @Test
    void importsMultipleWorkbooksAndAggregatesCounts() throws Exception {
        Path first = writeWorkbook();
        Path second = writeWorkbook();

        ConfigImportBatchResult result = service.importWorkbooks(List.of(
                new ConfigImportFile(first, "A825+comm+张三.xlsx"),
                new ConfigImportFile(second, "A825+loan+李四.xlsx")
        ), "S030030014FcyCollCrspBnkLkgQry", null, "李四");

        assertThat(result.results()).hasSize(2);
        assertThat(result.tranInserted()).isEqualTo(1);
        assertThat(result.tranUpdated()).isEqualTo(1);
        assertThat(result.fieldInserted()).isEqualTo(4);
        assertThat(result.fieldUpdated()).isEqualTo(4);
        String owner = jdbc.queryForObject("""
                select owner from ana_tran_catalog
                where tran_code = :tranCode and service_code = :serviceCode
                """, params(), String.class);
        assertThat(owner).isEqualTo("李四");
    }

    @Test
    void importsBlankServiceCodeFromServiceNameAndOperationNameAndKeepsBlankOwner() throws Exception {
        Path workbook = writeWorkbook();

        ConfigImportResult result = service.importWorkbook(workbook, "A825+comm+张三.xlsx",
                "", null, "");

        assertThat(result.tranInserted()).isEqualTo(1);
        String owner = jdbc.queryForObject("""
                select owner from ana_tran_catalog
                where tran_code = :tranCode and service_code = :serviceCode
                """, new MapSqlParameterSource()
                .addValue("tranCode", "A825")
                .addValue("serviceCode", "S030030014FcyCollCrspBnkLkgQry"), String.class);
        assertThat(owner).isEqualTo("");
    }

    @Test
    void importsAllTransactionsFromRestoredWorkbook() throws Exception {
        ConfigImportBatchResult result = service.importWorkbooks(List.of(
                new ConfigImportFile(Path.of("11_22_restored.xlsx"), "11_22_restored.xlsx")
        ), "", "", "");

        assertThat(result.results()).hasSize(3);
        assertThat(result.tranInserted()).isEqualTo(3);
        assertThat(result.fieldInserted()).isEqualTo(12);

        List<String> tranCodes = jdbc.query("""
                select tran_code from ana_tran_catalog order by tran_code
                """, (rs, rowNum) -> rs.getString("tran_code"));
        assertThat(tranCodes).containsExactly("A825", "A826", "A827");

        List<String> serviceCodes = jdbc.query("""
                select service_code from ana_tran_catalog order by tran_code
                """, (rs, rowNum) -> rs.getString("service_code"));
        assertThat(serviceCodes).containsExactly(
                "S030030014FcyCollCrspBnkLkgQry",
                "S030030015FcyCollCrspBnkLkgQry",
                "S030030016FcyCollCrspBnkLkgQry"
        );

        Integer fieldCount = jdbc.queryForObject("""
                select count(*) from ana_field_mapping
                """, new MapSqlParameterSource(), Integer.class);
        assertThat(fieldCount).isEqualTo(12);

        List<String> owners = jdbc.query("""
                select distinct owner from ana_tran_catalog
                """, (rs, rowNum) -> rs.getString("owner"));
        assertThat(owners).containsExactly("");
    }

    @Test
    void importsParsedSheetsWithMetadataFromTransactionListEntries() throws Exception {
        try (var workbook = ConfigWorkbookParserTest.a825Workbook()) {
            ConfigImportBatchResult result = service.importParsedWorkbooks(
                    List.of(workbook),
                    List.of(new TransactionListEntry("A825", "存款", "张三/李四"))
            );

            assertThat(result.tranInserted()).isEqualTo(1);
            assertThat(result.fieldInserted()).isEqualTo(4);
            String moduleName = jdbc.queryForObject("""
                    select module_name from ana_tran_catalog
                    where tran_code = :tranCode and service_code = :serviceCode
                    """, params(), String.class);
            String owner = jdbc.queryForObject("""
                    select owner from ana_tran_catalog
                    where tran_code = :tranCode and service_code = :serviceCode
                    """, params(), String.class);
            assertThat(moduleName).isEqualTo("存款");
            assertThat(owner).isEqualTo("张三/李四");
        }
    }

    private MapSqlParameterSource params() {
        return new MapSqlParameterSource()
                .addValue("tranCode", "A825")
                .addValue("serviceCode", "S030030014FcyCollCrspBnkLkgQry");
    }

    private Path writeWorkbook() throws Exception {
        Path file = Files.createTempFile("A825+comm+张三", ".xlsx");
        try (var workbook = ConfigWorkbookParserTest.a825Workbook();
             OutputStream output = Files.newOutputStream(file)) {
            workbook.write(output);
        }
        return file;
    }
}
