package com.spdb.config;

import org.apache.poi.ss.usermodel.Workbook;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.web.client.RestClient;

import java.io.ByteArrayOutputStream;
import java.lang.reflect.Constructor;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class TransactionListImportTaskRunnerTest {
    private NamedParameterJdbcTemplate jdbc;
    private TransactionListImportTaskService taskService;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:transaction_list_import_runner;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        jdbc = new NamedParameterJdbcTemplate(dataSource);
        jdbc.getJdbcTemplate().execute("drop table if exists ana_transaction_list_import_task");
        jdbc.getJdbcTemplate().execute("drop table if exists ana_field_mapping");
        jdbc.getJdbcTemplate().execute("drop table if exists ana_tran_catalog");
        jdbc.getJdbcTemplate().execute("""
                create table ana_transaction_list_import_task (
                    task_id bigint generated by default as identity primary key,
                    status varchar(32) not null default 'CREATED',
                    original_filename varchar(255),
                    list_file_path varchar(1000) not null,
                    total_count integer not null default 0,
                    request_batch_count integer not null default 0,
                    completed_batch_count integer not null default 0,
                    failed_batch_count integer not null default 0,
                    imported_count integer not null default 0,
                    tran_inserted integer not null default 0,
                    tran_updated integer not null default 0,
                    field_inserted integer not null default 0,
                    field_updated integer not null default 0,
                    field_skipped integer not null default 0,
                    failure_message varchar(4000),
                    created_time timestamp default current_timestamp,
                    started_time timestamp,
                    ended_time timestamp,
                    updated_at timestamp default current_timestamp
                )
                """);
        jdbc.getJdbcTemplate().execute("""
                create table ana_tran_catalog (
                    catalog_id bigint generated by default as identity primary key,
                    tran_code varchar(32) not null,
                    service_code varchar(200) not null,
                    tran_name varchar(200),
                    module_name varchar(100),
                    owner varchar(100),
                    importance_level varchar(32),
                    is_key_tran varchar(5),
                    remark varchar(1000),
                    created_at timestamp default current_timestamp,
                    updated_at timestamp default current_timestamp,
                    unique (tran_code, service_code)
                )
                """);
        jdbc.getJdbcTemplate().execute("""
                create table ana_field_mapping (
                    mapping_id bigint generated by default as identity primary key,
                    tran_code varchar(32) not null,
                    service_code varchar(200) not null,
                    std_field_name varchar(200) not null,
                    field_cn_name varchar(200),
                    sop_field_name varchar(200),
                    soap_field_name varchar(200),
                    bizjson_field_name varchar(200),
                    remark varchar(1000),
                    created_at timestamp default current_timestamp,
                    updated_at timestamp default current_timestamp,
                    unique (tran_code, service_code, std_field_name)
                )
                """);
        taskService = new TransactionListImportTaskService(jdbc, emptyLauncherProvider());
    }

    @Test
    void retriesDownloadFailuresAndUpdatesTaskProgress() throws Exception {
        Path listWorkbook = TransactionListImportServiceTestData.writeTransactionListWorkbook("A825");
        RetryingMappingDocumentClient client = new RetryingMappingDocumentClient(mappingWorkbookBytes(), 2);
        ConfigImportService configImportService = new ConfigImportService(new ConfigWorkbookParser(), jdbc);
        TransactionListImportService importService = new TransactionListImportService(
                new TransactionListWorkbookParser(),
                client,
                configImportService
        );
        TransactionListImportTaskRunner runner = new TransactionListImportTaskRunner(
                taskService,
                new TransactionListWorkbookParser(),
                client,
                importService,
                configImportService,
                false
        );
        long taskId = taskService.createTask(listWorkbook, "list.xlsx");

        runner.run(taskId);

        TransactionListImportProgressRow progress = taskService.progress(taskId);
        assertThat(client.attempts()).isEqualTo(3);
        assertThat(progress.status()).isEqualTo("COMPLETED");
        assertThat(progress.totalCount()).isEqualTo(1);
        assertThat(progress.requestBatchCount()).isEqualTo(1);
        assertThat(progress.completedBatchCount()).isEqualTo(1);
        assertThat(progress.failedBatchCount()).isZero();
        assertThat(progress.importedCount()).isEqualTo(1);
        assertThat(progress.fieldInserted()).isEqualTo(4);
    }

    @Test
    void productionConstructorIsMarkedForSpringInjection() throws Exception {
        Constructor<TransactionListImportTaskRunner> constructor = TransactionListImportTaskRunner.class.getConstructor(
                TransactionListImportTaskService.class,
                TransactionListWorkbookParser.class,
                MappingDocumentClient.class,
                TransactionListImportService.class,
                ConfigImportService.class
        );

        assertThat(constructor.getAnnotation(Autowired.class)).isNotNull();
    }

    private ObjectProvider<TransactionListImportTaskLauncher> emptyLauncherProvider() {
        return new ObjectProvider<>() {
            @Override
            public TransactionListImportTaskLauncher getObject(Object... args) {
                return null;
            }

            @Override
            public TransactionListImportTaskLauncher getIfAvailable() {
                return null;
            }

            @Override
            public TransactionListImportTaskLauncher getIfUnique() {
                return null;
            }

            @Override
            public TransactionListImportTaskLauncher getObject() {
                return null;
            }
        };
    }

    private byte[] mappingWorkbookBytes() {
        try (Workbook workbook = ConfigWorkbookParserTest.a825Workbook();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            workbook.write(out);
            return out.toByteArray();
        } catch (Exception ex) {
            throw new AssertionError(ex);
        }
    }

    private static class RetryingMappingDocumentClient extends MappingDocumentClient {
        private final byte[] response;
        private final int failuresBeforeSuccess;
        private int attempts;

        RetryingMappingDocumentClient(byte[] response, int failuresBeforeSuccess) {
            super(RestClient.builder().build(), new MappingDocumentProperties("http://server/download?param=multi,{codes},MAPPING9", 10));
            this.response = response;
            this.failuresBeforeSuccess = failuresBeforeSuccess;
        }

        @Override
        public byte[] download(List<String> tranCodes) {
            attempts++;
            if (attempts <= failuresBeforeSuccess) {
                throw new IllegalStateException("temporary outage");
            }
            return response;
        }

        int attempts() {
            return attempts;
        }
    }

    private static class TransactionListImportServiceTestData {
        static Path writeTransactionListWorkbook(String tranCode) throws Exception {
            Path file = Files.createTempFile("transaction-list", ".xlsx");
            try (Workbook workbook = new org.apache.poi.xssf.usermodel.XSSFWorkbook();
                 var out = Files.newOutputStream(file)) {
                var sheet = workbook.createSheet("mapping");
                var row = sheet.createRow(2);
                row.createCell(0).setCellValue("module");
                row.createCell(3).setCellValue(tranCode);
                row.createCell(7).setCellValue("dev");
                row.createCell(8).setCellValue("biz");
                workbook.write(out);
            }
            return file;
        }
    }
}
