package com.spdb.config;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.read.ListAppender;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.web.client.RestClient;

import java.io.ByteArrayOutputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

class TransactionListImportServiceTest {

    private NamedParameterJdbcTemplate jdbc;
    private TransactionListImportService service;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource("jdbc:h2:mem:transaction_list_import;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1", "sa", "");
        jdbc = new NamedParameterJdbcTemplate(dataSource);
        jdbc.getJdbcTemplate().execute("drop table if exists ana_field_mapping");
        jdbc.getJdbcTemplate().execute("drop table if exists ana_tran_catalog");
        jdbc.getJdbcTemplate().execute("""
                create table ana_tran_catalog (
                    catalog_id bigint generated by default as identity primary key,
                    tran_code varchar(32) not null,
                    service_code varchar(200) not null,
                    tran_name varchar(200),
                    module_name varchar(100),
                    owner varchar(100),
                    importance_level varchar(32),
                    is_key_tran varchar(5),
                    remark varchar(1000),
                    created_at timestamp default current_timestamp,
                    updated_at timestamp default current_timestamp,
                    unique (tran_code, service_code)
                )
                """);
        jdbc.getJdbcTemplate().execute("""
                create table ana_field_mapping (
                    mapping_id bigint generated by default as identity primary key,
                    tran_code varchar(32) not null,
                    service_code varchar(200) not null,
                    std_field_name varchar(200) not null,
                    field_cn_name varchar(200),
                    sop_field_name varchar(200),
                    soap_field_name varchar(200),
                    bizjson_field_name varchar(200),
                    remark varchar(1000),
                    created_at timestamp default current_timestamp,
                    updated_at timestamp default current_timestamp,
                    unique (tran_code, service_code, std_field_name)
                )
                """);
        MappingDocumentClient client = new StubMappingDocumentClient(mappingWorkbookBytes());
        service = new TransactionListImportService(
                new TransactionListWorkbookParser(),
                client,
                new ConfigImportService(new ConfigWorkbookParser(), jdbc)
        );
    }

    @Test
    void importsTransactionListByDownloadingMappingWorkbookBatches() throws Exception {
        Path listWorkbook = writeTransactionListWorkbook();

        TransactionListImportResult result = service.importList(listWorkbook);

        assertThat(result.totalCount()).isEqualTo(1);
        assertThat(result.requestBatchCount()).isEqualTo(1);
        assertThat(result.successBatchCount()).isEqualTo(1);
        assertThat(result.failureBatchCount()).isZero();
        assertThat(result.importResult().tranInserted()).isEqualTo(1);
        assertThat(result.importResult().fieldInserted()).isEqualTo(4);
        assertThat(result.failures()).isEmpty();

        String owner = jdbc.queryForObject("""
                select owner from ana_tran_catalog
                where tran_code = :tranCode
                """, new MapSqlParameterSource("tranCode", "A825"), String.class);
        assertThat(owner).isEqualTo("张三/李四");
    }

    @Test
    void recordsFailureWhenReturnedWorkbookDoesNotContainListedTransactionCode() throws Exception {
        Path listWorkbook = writeTransactionListWorkbook("C999");

        TransactionListImportResult result = service.importList(listWorkbook);

        assertThat(result.importResult().tranInserted()).isZero();
        assertThat(result.failures()).contains("C999: 未在映射文档中找到交易码");
    }

    @Test
    void logsBatchProgressWhenImportingTransactionList() throws Exception {
        Path listWorkbook = writeTransactionListWorkbook();

        ListAppender<ILoggingEvent> appender = attachAppender();
        try {
            service.importList(listWorkbook);
        } finally {
            detachAppender(appender);
        }

        assertThat(appender.list).anySatisfy(event -> {
            assertThat(event.getLevel()).isEqualTo(Level.INFO);
            assertThat(event.getFormattedMessage())
                    .contains("Transaction list mapping download batch started")
                    .contains("batch=1/1")
                    .contains("tranCount=1");
        });
        assertThat(appender.list).anySatisfy(event -> {
            assertThat(event.getLevel()).isEqualTo(Level.INFO);
            assertThat(event.getFormattedMessage())
                    .contains("Transaction list import completed")
                    .contains("totalCount=1")
                    .contains("successBatchCount=1");
        });
    }

    private Path writeTransactionListWorkbook() throws Exception {
        return writeTransactionListWorkbook("A825");
    }

    private Path writeTransactionListWorkbook(String tranCode) throws Exception {
        Path file = Files.createTempFile("transaction-list", ".xlsx");
        try (Workbook workbook = new XSSFWorkbook();
             var out = Files.newOutputStream(file)) {
            var sheet = workbook.createSheet("接口映射表");
            var header = sheet.createRow(1);
            header.createCell(0).setCellValue("业务领域");
            header.createCell(3).setCellValue("防腐528交易码");
            header.createCell(7).setCellValue("开发负责人");
            header.createCell(8).setCellValue("业务负责人");
            var row = sheet.createRow(2);
            row.createCell(0).setCellValue("存款");
            row.createCell(3).setCellValue(tranCode);
            row.createCell(7).setCellValue("张三");
            row.createCell(8).setCellValue("李四");
            workbook.write(out);
        }
        return file;
    }

    private byte[] mappingWorkbookBytes() {
        try (Workbook workbook = ConfigWorkbookParserTest.a825Workbook();
             ByteArrayOutputStream out = new ByteArrayOutputStream()) {
            workbook.write(out);
            return out.toByteArray();
        } catch (Exception ex) {
            throw new AssertionError(ex);
        }
    }

    private ListAppender<ILoggingEvent> attachAppender() {
        Logger logger = (Logger) LoggerFactory.getLogger(TransactionListImportService.class);
        ListAppender<ILoggingEvent> appender = new ListAppender<>();
        appender.start();
        logger.addAppender(appender);
        return appender;
    }

    private void detachAppender(ListAppender<ILoggingEvent> appender) {
        Logger logger = (Logger) LoggerFactory.getLogger(TransactionListImportService.class);
        logger.detachAppender(appender);
    }

    private static class StubMappingDocumentClient extends MappingDocumentClient {
        private final byte[] response;

        StubMappingDocumentClient(byte[] response) {
            super(RestClient.builder().build(), new MappingDocumentProperties("http://server/download?param=multi,{codes},MAPPING9", 10));
            this.response = response;
        }

        @Override
        public byte[] download(List<String> tranCodes) {
            return response;
        }
    }
}
