package com.spdb.config;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

class TransactionListImportTaskServiceTest {
    private JdbcTemplate plainJdbc;
    private RecordingLauncher launcher;
    private TransactionListImportTaskService service;

    @BeforeEach
    void setUp() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:transaction_list_import_task;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1",
                "sa",
                ""
        );
        NamedParameterJdbcTemplate jdbc = new NamedParameterJdbcTemplate(dataSource);
        plainJdbc = new JdbcTemplate(dataSource);
        plainJdbc.execute("drop table if exists ana_transaction_list_import_task");
        plainJdbc.execute("""
                create table ana_transaction_list_import_task (
                    task_id bigint generated by default as identity primary key,
                    status varchar(32) not null default 'CREATED',
                    original_filename varchar(255),
                    list_file_path varchar(1000) not null,
                    total_count integer not null default 0,
                    request_batch_count integer not null default 0,
                    completed_batch_count integer not null default 0,
                    failed_batch_count integer not null default 0,
                    imported_count integer not null default 0,
                    tran_inserted integer not null default 0,
                    tran_updated integer not null default 0,
                    field_inserted integer not null default 0,
                    field_updated integer not null default 0,
                    field_skipped integer not null default 0,
                    imported_tran_codes clob,
                    failure_message varchar(4000),
                    created_time timestamp default current_timestamp,
                    started_time timestamp,
                    ended_time timestamp,
                    updated_at timestamp default current_timestamp
                )
                """);
        launcher = new RecordingLauncher();
        service = new TransactionListImportTaskService(jdbc, launcherProvider(launcher));
    }

    @Test
    void createTaskPersistsUploadAndLaunchesBackgroundWork() {
        long taskId = service.createTask(Path.of("C:/tmp/list.xlsx"), "金融业务交易信息登记表.xlsx");

        TransactionListImportProgressRow progress = service.progress(taskId);
        assertThat(progress.taskId()).isEqualTo(taskId);
        assertThat(progress.status()).isEqualTo("CREATED");
        assertThat(progress.originalFilename()).isEqualTo("金融业务交易信息登记表.xlsx");
        assertThat(progress.totalCount()).isZero();
        assertThat(launcher.launchedTaskId()).isEqualTo(taskId);
    }

    @Test
    void progressCountersCanBeUpdatedUntilCompletion() {
        long taskId = service.createTask(Path.of("C:/tmp/list.xlsx"), "list.xlsx");

        assertThat(service.markRunning(taskId)).isTrue();
        service.updatePlannedCounts(taskId, 25, 3);
        service.incrementCompletedBatch(taskId);
        service.incrementFailedBatch(taskId, "A001,A002: timeout");
        service.recordSuccessfulImportChunk(taskId, new ConfigImportBatchResult(
                2, 1, 7, 3, 4, java.util.List.of(
                resultFor("A001"),
                resultFor("A002"),
                resultFor("A003")
        )));
        service.markCompleted(taskId, new ConfigImportBatchResult(0, 0, 0, 0, 0, java.util.List.of()), 3, "C999: missing");

        TransactionListImportProgressRow progress = service.progress(taskId);
        assertThat(progress.status()).isEqualTo("COMPLETED");
        assertThat(progress.totalCount()).isEqualTo(25);
        assertThat(progress.requestBatchCount()).isEqualTo(3);
        assertThat(progress.completedBatchCount()).isEqualTo(1);
        assertThat(progress.failedBatchCount()).isEqualTo(1);
        assertThat(progress.importedCount()).isEqualTo(3);
        assertThat(progress.tranInserted()).isEqualTo(2);
        assertThat(progress.fieldInserted()).isEqualTo(7);
        assertThat(progress.failureMessage()).contains("timeout").contains("missing");
    }

    @Test
    void successfulImportChunksAreRecordedForResume() {
        long taskId = service.createTask(Path.of("C:/tmp/list.xlsx"), "list.xlsx");

        assertThat(service.markRunning(taskId)).isTrue();
        service.recordSuccessfulImportChunk(taskId, new ConfigImportBatchResult(
                2, 1, 7, 3, 4, java.util.List.of(
                resultFor("A001"),
                resultFor("A002"),
                resultFor("A003")
        )));
        service.markFailed(taskId, "A004: failed");

        assertThat(service.importedTranCodes(taskId)).containsExactlyInAnyOrder("A001", "A002", "A003");
        TransactionListImportProgressRow progress = service.progress(taskId);
        assertThat(progress.status()).isEqualTo("FAILED");
        assertThat(progress.importedCount()).isEqualTo(3);
        assertThat(progress.tranInserted()).isEqualTo(2);
        assertThat(progress.tranUpdated()).isEqualTo(1);
        assertThat(progress.fieldInserted()).isEqualTo(7);
        assertThat(progress.fieldUpdated()).isEqualTo(3);
        assertThat(progress.fieldSkipped()).isEqualTo(4);

        assertThat(service.markRunning(taskId)).isTrue();
        assertThat(service.importedTranCodes(taskId)).containsExactlyInAnyOrder("A001", "A002", "A003");
        assertThat(service.progress(taskId).importedCount()).isEqualTo(3);
    }

    @Test
    void markFailedStoresAbbreviatedFailureMessage() {
        long taskId = service.createTask(Path.of("C:/tmp/list.xlsx"), "list.xlsx");

        service.markRunning(taskId);
        service.markFailed(taskId, "download failed");

        TransactionListImportProgressRow progress = service.progress(taskId);
        assertThat(progress.status()).isEqualTo("FAILED");
        assertThat(progress.failureMessage()).isEqualTo("download failed");
        assertThat(plainJdbc.queryForObject(
                "select count(*) from ana_transaction_list_import_task where status = 'FAILED'",
                Long.class
        )).isEqualTo(1L);
    }

    private ObjectProvider<TransactionListImportTaskLauncher> launcherProvider(TransactionListImportTaskLauncher launcher) {
        return new ObjectProvider<>() {
            @Override
            public TransactionListImportTaskLauncher getObject(Object... args) {
                return launcher;
            }

            @Override
            public TransactionListImportTaskLauncher getIfAvailable() {
                return launcher;
            }

            @Override
            public TransactionListImportTaskLauncher getIfUnique() {
                return launcher;
            }

            @Override
            public TransactionListImportTaskLauncher getObject() {
                return launcher;
            }
        };
    }

    private ConfigImportResult resultFor(String tranCode) {
        return new ConfigImportResult(
                1,
                0,
                1,
                0,
                0,
                new ParsedConfigImport(
                        new ParsedTranImport(tranCode, "SVC_" + tranCode, "tran", "module", "owner", "remark"),
                        java.util.List.of(),
                        java.util.List.of()
                )
        );
    }

    private static class RecordingLauncher implements TransactionListImportTaskLauncher {
        private long launchedTaskId;

        @Override
        public void launch(long taskId) {
            this.launchedTaskId = taskId;
        }

        long launchedTaskId() {
            return launchedTaskId;
        }
    }
}
